import { getDataLastModified } from "@/lib/data";

const BASE_URL = "https://signals.gitdealflow.com";

// Sitemap index. Lists every shard generated by /sitemap/[id]/route.ts.
// Search Console expects an explicit sitemap-index XML at /sitemap.xml when
// the underlying URL set is paginated. Without this, robots.txt's
// `Sitemap: /sitemap.xml` directive resolves to nothing.
export async function GET() {
  const lastmod = getDataLastModified().toISOString();

  const shards = ["core", "sectors", "crossings", "startups", "content", "i18n"];

  const sitemapsXml = shards
    .map(
      (id) =>
        `  <sitemap>\n    <loc>${BASE_URL}/sitemap/${id}.xml</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>`
    )
    .join("\n");

  const body = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapsXml}\n</sitemapindex>\n`;

  return new Response(body, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "s-maxage=3600, stale-while-revalidate=86400",
      "X-Robots-Tag": "index, follow",
    },
  });
}
