/**
 * /signal/[slug] entity pages — per-company GitHub engineering signal reports.
 *
 * Seed corpus of public, well-known startups and scale-ups that maintain a
 * visible GitHub org. Each entry powers one /signal/{slug} page with
 * Organization JSON-LD, BreadcrumbList, FAQPage, and a CTA into /firstlook.
 *
 * Privacy posture: only companies whose engineering operations are already
 * matter-of-fact public (the company self-publishes its GitHub org on its
 * homepage, devrel blog, or hiring page). No private orgs, no leaked
 * employee data, no inferred-from-LinkedIn personal data — only signals
 * derivable from public GitHub events.
 *
 * Signal scores are static placeholders for the v1 ship; a follow-up PR
 * will join these slugs against lib/data.ts and the weekly Top 100 to
 * populate live numbers. The page renders identically either way.
 */

export interface CompanyFAQ {
  question: string;
  answer: string;
}

export interface Company {
  slug: string;
  name: string;
  githubOrg: string;
  homepageUrl: string;
  sector: string;
  stage: "seed" | "series-a" | "series-b" | "series-c" | "later" | "public";
  description: string;
  // SEO surfaces
  title: string;
  metaDescription: string;
  h1: string;
  tagline: string;
  intro: string;
  signalSummary: string;
  whatWeTrack: string;
  whyItMatters: string;
  // Static placeholder until live signal join lands
  publicSignal: {
    momentum: "accelerating" | "steady" | "decelerating" | "unranked";
    publicReposEstimate: string;
    languageBias: string;
  };
  faqs: CompanyFAQ[];
  relatedSectors: string[];
}

// Concise content generator — each entry overrides only the fields that
// differ. Keeps the seed corpus tight while ensuring every page has
// unique title, description, intro, and FAQs.
function build(c: {
  slug: string;
  name: string;
  githubOrg: string;
  homepage: string;
  sector: string;
  stage: Company["stage"];
  what: string;
  momentum: Company["publicSignal"]["momentum"];
  repos: string;
  lang: string;
  related: string[];
}): Company {
  const stageLabel = c.stage === "public" ? "public" : `${c.stage.replace("-", " ")}`;
  return {
    slug: c.slug,
    name: c.name,
    githubOrg: c.githubOrg,
    homepageUrl: c.homepage,
    sector: c.sector,
    stage: c.stage,
    description: `${c.name} (${c.sector}, ${stageLabel}) — GitHub org github.com/${c.githubOrg}. ${c.what}`,
    title: `${c.name} GitHub Engineering Signals (2026) — VC Deal Flow Signal`,
    metaDescription: `${c.name} GitHub activity: commit velocity, contributor influx, repo expansion, and language bias. A quantitative view of ${c.name}'s engineering trajectory for investors and operators.`,
    h1: `${c.name} GitHub Engineering Signals`,
    tagline: `A quantitative view of ${c.name}'s public engineering activity — what we track and why investors watch it.`,
    intro: `${c.name} (${c.sector}, ${stageLabel}) is one of the public technical companies VC Deal Flow Signal monitors via the github.com/${c.githubOrg} org. ${c.what} Investors who source deals in ${c.sector} often watch ${c.name} as a benchmark — its commit velocity, contributor influx, and infrastructure repo growth set the reference curve for what "accelerating" looks like in this sector.`,
    signalSummary: `Current ${c.name} engineering signal: ${c.momentum}. Public repo footprint ${c.repos}. Primary language bias: ${c.lang}. Updated weekly from public GitHub events.`,
    whatWeTrack: `For ${c.name}, we monitor: (1) Commit velocity across the public org versus the trailing 12-week median, (2) Contributor influx — net new active contributors per week, (3) Repo creation pulse and infrastructure repo buildouts, (4) Language and dependency shifts that signal product pivots, (5) Issue cadence and external community engagement.`,
    whyItMatters: `${c.name} sits at an interesting point in the ${c.sector} engineering curve. For investors, the signal is twofold: it informs sector benchmarks (is this category accelerating or saturating), and it surfaces adjacent breakout candidates — early-stage startups whose engineering acceleration matches ${c.name}'s pattern 12-18 months ago.`,
    publicSignal: {
      momentum: c.momentum,
      publicReposEstimate: c.repos,
      languageBias: c.lang,
    },
    faqs: [
      {
        question: `What data does VC Deal Flow Signal collect about ${c.name}?`,
        answer: `Only public GitHub events: commits, PRs, issues, releases, and contributor activity from github.com/${c.githubOrg}. We do not collect employee personal data, private repo content, or any signal that is not already publicly visible on GitHub.com. This page is generated from public-events aggregations.`,
      },
      {
        question: `Is ${c.name} a recommendation or endorsement?`,
        answer: `No. This page is a quantitative view of public engineering activity. It is not investment advice and not an endorsement. ${c.name} has not paid for placement and is not affiliated with VC Deal Flow Signal.`,
      },
      {
        question: `How often is this updated?`,
        answer: `Signal aggregates refresh weekly from public GitHub events. Page-level lastmod is published in the sitemap. For real-time signal access, see /firstlook or the public MCP server at /api/v1.`,
      },
      {
        question: `How is ${c.name}'s momentum measured?`,
        answer: `Momentum is derived from commit-velocity acceleration (rolling 4-week mean vs trailing 12-week median), contributor influx, and repo creation pulse — the same six-signal panel published in /methodology and the open paper at SSRN 6606558.`,
      },
    ],
    relatedSectors: c.related,
  };
}

export const companies: Company[] = [
  build({
    slug: "vercel",
    name: "Vercel",
    githubOrg: "vercel",
    homepage: "https://vercel.com",
    sector: "developer-tools",
    stage: "later",
    what: "Vercel ships the frontend cloud (Next.js, hosting, AI SDK, AI Gateway, Workflow, Sandbox). Their public org is one of the most active in the developer-tools sector.",
    momentum: "accelerating",
    repos: "300+ active public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "ai-ml", "infrastructure"],
  }),
  build({
    slug: "supabase",
    name: "Supabase",
    githubOrg: "supabase",
    homepage: "https://supabase.com",
    sector: "developer-tools",
    stage: "series-c",
    what: "Open-source Firebase alternative — Postgres-native backend, auth, storage, edge functions. Their commit velocity has compounded steadily since the 2020 launch.",
    momentum: "accelerating",
    repos: "200+ active public repos",
    lang: "TypeScript / Go",
    related: ["developer-tools", "database", "infrastructure"],
  }),
  build({
    slug: "resend",
    name: "Resend",
    githubOrg: "resend",
    homepage: "https://resend.com",
    sector: "developer-tools",
    stage: "series-a",
    what: "Email API for developers. SDKs across every major runtime; React Email is the de facto template library. A textbook case of API-first developer-tools growth.",
    momentum: "accelerating",
    repos: "60+ active public repos",
    lang: "TypeScript",
    related: ["developer-tools", "api-platforms"],
  }),
  build({
    slug: "posthog",
    name: "PostHog",
    githubOrg: "PostHog",
    homepage: "https://posthog.com",
    sector: "analytics",
    stage: "series-c",
    what: "Open-source product analytics — events, session replay, feature flags, A/B tests, LLM observability, all in one self-hostable platform.",
    momentum: "accelerating",
    repos: "100+ active public repos",
    lang: "Python / TypeScript",
    related: ["analytics", "developer-tools", "ai-ml"],
  }),
  build({
    slug: "linear",
    name: "Linear",
    githubOrg: "linear",
    homepage: "https://linear.app",
    sector: "productivity",
    stage: "series-c",
    what: "Issue tracking and product management for software teams. Their public SDK and API ecosystem ship steady weekly updates.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "convex",
    name: "Convex",
    githubOrg: "get-convex",
    homepage: "https://convex.dev",
    sector: "database",
    stage: "series-b",
    what: "Reactive backend platform — database, queries, mutations, file storage, scheduling, all in one TypeScript-native runtime.",
    momentum: "accelerating",
    repos: "50+ active public repos",
    lang: "TypeScript / Rust",
    related: ["database", "developer-tools", "ai-ml"],
  }),
  build({
    slug: "neon",
    name: "Neon",
    githubOrg: "neondatabase",
    homepage: "https://neon.tech",
    sector: "database",
    stage: "series-c",
    what: "Serverless Postgres with branching. The standard managed Postgres choice for AI-era developer-tools companies.",
    momentum: "accelerating",
    repos: "40+ active public repos",
    lang: "Rust / TypeScript",
    related: ["database", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "modal",
    name: "Modal",
    githubOrg: "modal-labs",
    homepage: "https://modal.com",
    sector: "ai-infra",
    stage: "series-b",
    what: "Serverless compute for AI — train, fine-tune, serve, and orchestrate Python workloads with sub-second cold starts on GPUs.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Python",
    related: ["ai-ml", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "replicate",
    name: "Replicate",
    githubOrg: "replicate",
    homepage: "https://replicate.com",
    sector: "ai-infra",
    stage: "series-b",
    what: "Run open-source ML models with an API. Their Cog runtime is one of the most-forked packaging standards in OSS ML.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "Python / Go",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "anthropic",
    name: "Anthropic",
    githubOrg: "anthropics",
    homepage: "https://www.anthropic.com",
    sector: "ai-ml",
    stage: "later",
    what: "Frontier AI lab — Claude model family, MCP protocol, Claude Code CLI, Claude Agent SDK. Their MCP standardization is reshaping the entire agentic ecosystem.",
    momentum: "accelerating",
    repos: "30+ active public repos",
    lang: "TypeScript / Python",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "openai",
    name: "OpenAI",
    githubOrg: "openai",
    homepage: "https://openai.com",
    sector: "ai-ml",
    stage: "later",
    what: "Closed-weight frontier lab whose open-source presence (SDKs, gym, whisper, evals) defines the public surface area for AI infrastructure.",
    momentum: "steady",
    repos: "100+ public repos (legacy + active)",
    lang: "Python / TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "mistral-ai",
    name: "Mistral AI",
    githubOrg: "mistralai",
    homepage: "https://mistral.ai",
    sector: "ai-ml",
    stage: "series-b",
    what: "Open-weight European frontier lab. Their public Mistral and Mixtral checkpoints are a benchmark for permissive-license LLM releases.",
    momentum: "accelerating",
    repos: "15+ active public repos",
    lang: "Python",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "cohere",
    name: "Cohere",
    githubOrg: "cohere-ai",
    homepage: "https://cohere.com",
    sector: "ai-ml",
    stage: "series-c",
    what: "Enterprise-focused LLM provider — strong retrieval and embeddings stack, growing agent and tool-use layer.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "huggingface",
    name: "Hugging Face",
    githubOrg: "huggingface",
    homepage: "https://huggingface.co",
    sector: "ai-ml",
    stage: "later",
    what: "The default model hub for open-weight AI. Transformers, datasets, diffusers, accelerate — the entire OSS ML stack ships through this org.",
    momentum: "accelerating",
    repos: "300+ active public repos",
    lang: "Python / Rust",
    related: ["ai-ml", "developer-tools", "infrastructure"],
  }),
  build({
    slug: "stripe",
    name: "Stripe",
    githubOrg: "stripe",
    homepage: "https://stripe.com",
    sector: "fintech",
    stage: "later",
    what: "Payments infrastructure. Their public SDK org is a long-running baseline of what a mature, multi-language, API-first engineering organization looks like.",
    momentum: "steady",
    repos: "200+ public repos across language SDKs",
    lang: "Ruby / Go / TypeScript",
    related: ["fintech", "developer-tools", "api-platforms"],
  }),
  build({
    slug: "cloudflare",
    name: "Cloudflare",
    githubOrg: "cloudflare",
    homepage: "https://www.cloudflare.com",
    sector: "infrastructure",
    stage: "public",
    what: "Edge platform — Workers, R2, D1, Hyperdrive, Durable Objects, AI Gateway. Their public org ships dozens of active repos across runtimes.",
    momentum: "accelerating",
    repos: "500+ active public repos",
    lang: "Rust / TypeScript",
    related: ["infrastructure", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "hashicorp",
    name: "HashiCorp",
    githubOrg: "hashicorp",
    homepage: "https://www.hashicorp.com",
    sector: "infrastructure",
    stage: "public",
    what: "Terraform, Vault, Consul, Nomad — the canonical infrastructure-as-code stack. Their public org is a long-running benchmark for OSS infra companies.",
    momentum: "steady",
    repos: "400+ public repos",
    lang: "Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "grafana",
    name: "Grafana Labs",
    githubOrg: "grafana",
    homepage: "https://grafana.com",
    sector: "observability",
    stage: "later",
    what: "Open-source observability — Grafana, Loki, Tempo, Mimir, Pyroscope. Their public org is one of the most active in monitoring tooling.",
    momentum: "accelerating",
    repos: "300+ public repos",
    lang: "Go / TypeScript",
    related: ["observability", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "sentry",
    name: "Sentry",
    githubOrg: "getsentry",
    homepage: "https://sentry.io",
    sector: "observability",
    stage: "later",
    what: "Open-source error monitoring and performance. Multi-language SDKs and the OSS Sentry server make this one of the most fork-able observability orgs.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Python / TypeScript",
    related: ["observability", "developer-tools"],
  }),
  build({
    slug: "prisma",
    name: "Prisma",
    githubOrg: "prisma",
    homepage: "https://www.prisma.io",
    sector: "developer-tools",
    stage: "series-b",
    what: "TypeScript ORM and database tooling. Strong public SDK presence and steady release cadence over multiple years.",
    momentum: "steady",
    repos: "60+ public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "database"],
  }),
  build({
    slug: "drizzle",
    name: "Drizzle",
    githubOrg: "drizzle-team",
    homepage: "https://orm.drizzle.team",
    sector: "developer-tools",
    stage: "seed",
    what: "TypeScript-first ORM that became the default Drizzle replacement choice in the AI-era stack. Fast-compounding GitHub presence.",
    momentum: "accelerating",
    repos: "20+ active public repos",
    lang: "TypeScript",
    related: ["developer-tools", "database"],
  }),
  build({
    slug: "clerk",
    name: "Clerk",
    githubOrg: "clerk",
    homepage: "https://clerk.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "User management for modern apps — auth, organizations, billing. Strong React/Next.js integration and growing multi-framework SDKs.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "trigger-dev",
    name: "Trigger.dev",
    githubOrg: "triggerdotdev",
    homepage: "https://trigger.dev",
    sector: "developer-tools",
    stage: "series-a",
    what: "Background jobs and durable workflows for developers. Open-core with a self-hostable runtime.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "inngest",
    name: "Inngest",
    githubOrg: "inngest",
    homepage: "https://www.inngest.com",
    sector: "developer-tools",
    stage: "series-a",
    what: "Event-driven workflow engine with strong AI-agent orchestration support. Open-source SDKs across runtimes.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "TypeScript / Go",
    related: ["developer-tools", "ai-ml", "infrastructure"],
  }),
  build({
    slug: "browserbase",
    name: "Browserbase",
    githubOrg: "browserbase",
    homepage: "https://www.browserbase.com",
    sector: "ai-infra",
    stage: "series-a",
    what: "Headless browser infrastructure for AI agents. One of the canonical picks for agent runtimes needing browser execution.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["ai-ml", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "e2b",
    name: "E2B",
    githubOrg: "e2b-dev",
    homepage: "https://e2b.dev",
    sector: "ai-infra",
    stage: "seed",
    what: "Sandboxed code execution for AI agents. Strong developer mindshare in the agent-runtime category.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript / Python",
    related: ["ai-ml", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "fly-io",
    name: "Fly.io",
    githubOrg: "superfly",
    homepage: "https://fly.io",
    sector: "infrastructure",
    stage: "series-b",
    what: "Global app platform — micro-VMs near users, with a strong Postgres and durable-objects layer.",
    momentum: "steady",
    repos: "60+ public repos",
    lang: "Go / Elixir / Rust",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "railway",
    name: "Railway",
    githubOrg: "railwayapp",
    homepage: "https://railway.app",
    sector: "infrastructure",
    stage: "series-a",
    what: "Heroku-style deploy platform with a sharp UI and a growing public SDK presence.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "upstash",
    name: "Upstash",
    githubOrg: "upstash",
    homepage: "https://upstash.com",
    sector: "infrastructure",
    stage: "series-a",
    what: "Serverless Redis and Kafka. A frequent default storage choice in the Vercel marketplace + AI-era stack.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "database", "developer-tools"],
  }),
  build({
    slug: "turso",
    name: "Turso",
    githubOrg: "tursodatabase",
    homepage: "https://turso.tech",
    sector: "database",
    stage: "series-a",
    what: "Edge SQLite (libSQL fork) for global low-latency reads. Heavy OSS contributions to libSQL.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / TypeScript",
    related: ["database", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "planetscale",
    name: "PlanetScale",
    githubOrg: "planetscale",
    homepage: "https://planetscale.com",
    sector: "database",
    stage: "series-c",
    what: "Serverless MySQL on Vitess. Public SDK and CLI shipped from a steady, multi-language org.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Go / TypeScript",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "stytch",
    name: "Stytch",
    githubOrg: "stytchauth",
    homepage: "https://stytch.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "Auth API for B2B and consumer apps. Multi-runtime SDKs with steady release cadence.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript / Go",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "workos",
    name: "WorkOS",
    githubOrg: "workos",
    homepage: "https://workos.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "Enterprise SSO, directory sync, audit logs — the SOC2-ready APIs that B2B SaaS bolts on for compliance.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Go / Ruby",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "fermyon",
    name: "Fermyon",
    githubOrg: "fermyon",
    homepage: "https://www.fermyon.com",
    sector: "infrastructure",
    stage: "series-a",
    what: "Wasm-native serverless platform — the canonical bet on WebAssembly as the next compute runtime.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Rust",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "fireworks-ai",
    name: "Fireworks AI",
    githubOrg: "fw-ai",
    homepage: "https://fireworks.ai",
    sector: "ai-infra",
    stage: "series-b",
    what: "Fast inference for open-weight LLMs and image models. One of the rotating top picks for cost-per-token-served.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python / Rust",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "together-ai",
    name: "Together AI",
    githubOrg: "togethercomputer",
    homepage: "https://www.together.ai",
    sector: "ai-infra",
    stage: "series-b",
    what: "Open-weight LLM training and inference. Heavy public OSS presence — RedPajama, Mamba, OpenChatKit.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Python",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "groq",
    name: "Groq",
    githubOrg: "groq",
    homepage: "https://groq.com",
    sector: "ai-infra",
    stage: "series-c",
    what: "LPU-based fast inference. Strong developer mindshare for sub-100ms LLM responses.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "dust-tt",
    name: "Dust",
    githubOrg: "dust-tt",
    homepage: "https://dust.tt",
    sector: "ai-ml",
    stage: "series-a",
    what: "AI-native workspace assistant for teams. Open-core platform with growing public agent surface area.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript / Rust",
    related: ["ai-ml", "productivity", "developer-tools"],
  }),
  build({
    slug: "cursor",
    name: "Cursor",
    githubOrg: "getcursor",
    homepage: "https://cursor.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "AI-first code editor that became the default IDE for AI-era engineers. Limited public surface but tracked closely by the sector.",
    momentum: "accelerating",
    repos: "5+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "lovable",
    name: "Lovable",
    githubOrg: "lovable-dev",
    homepage: "https://lovable.dev",
    sector: "ai-ml",
    stage: "series-a",
    what: "Vibe-coding platform — natural-language to full-stack web app. One of the most-discussed AI builder platforms of 2025-2026.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "remotion",
    name: "Remotion",
    githubOrg: "remotion-dev",
    homepage: "https://www.remotion.dev",
    sector: "developer-tools",
    stage: "series-a",
    what: "Programmatic video creation in React. The canonical pick for AI video pipelines and developer-built creative tools.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "ai-ml", "creative-tools"],
  }),
  build({
    slug: "tailwindcss",
    name: "Tailwind Labs",
    githubOrg: "tailwindlabs",
    homepage: "https://tailwindlabs.com",
    sector: "developer-tools",
    stage: "later",
    what: "Tailwind CSS, Headless UI, Heroicons. One of the longest-running and most influential public design-system orgs.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "design-systems"],
  }),
  build({
    slug: "shadcn",
    name: "shadcn",
    githubOrg: "shadcn-ui",
    homepage: "https://ui.shadcn.com",
    sector: "developer-tools",
    stage: "seed",
    what: "Component library by reference — copy-paste primitives that became the default React UI stack in 2024-2026.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "design-systems"],
  }),
  build({
    slug: "langchain",
    name: "LangChain",
    githubOrg: "langchain-ai",
    homepage: "https://www.langchain.com",
    sector: "ai-ml",
    stage: "series-b",
    what: "Most-forked AI-framework org — LangChain, LangGraph, LangSmith. Defines a large slice of the public agent-tooling surface.",
    momentum: "accelerating",
    repos: "60+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "crewai",
    name: "CrewAI",
    githubOrg: "crewAIInc",
    homepage: "https://www.crewai.com",
    sector: "ai-ml",
    stage: "seed",
    what: "Multi-agent orchestration framework with strong public mindshare in role-based agent design.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "letta-ai",
    name: "Letta",
    githubOrg: "letta-ai",
    homepage: "https://www.letta.com",
    sector: "ai-ml",
    stage: "seed",
    what: "Stateful agent framework (formerly MemGPT). The reference implementation for agent memory architectures.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "mastra",
    name: "Mastra",
    githubOrg: "mastra-ai",
    homepage: "https://mastra.ai",
    sector: "ai-ml",
    stage: "seed",
    what: "TypeScript-first agent framework with strong workflow primitives. One of the fastest-rising agent libraries in late 2025.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "elevenlabs",
    name: "ElevenLabs",
    githubOrg: "elevenlabs",
    homepage: "https://elevenlabs.io",
    sector: "ai-ml",
    stage: "series-c",
    what: "Voice synthesis and audio AI. Public SDKs across runtimes with steady release cadence.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript / Python",
    related: ["ai-ml", "developer-tools", "creative-tools"],
  }),
  build({
    slug: "perplexity-ai",
    name: "Perplexity",
    githubOrg: "perplexity-ai",
    homepage: "https://www.perplexity.ai",
    sector: "ai-ml",
    stage: "series-c",
    what: "Answer engine with proprietary retrieval and ranking. Limited but precise public surface.",
    momentum: "accelerating",
    repos: "5+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "search"],
  }),
  // ───────────────────────── 2026-05-28 expansion (15 orgs) ─────────────────────────
  build({
    slug: "mongodb",
    name: "MongoDB",
    githubOrg: "mongodb",
    homepage: "https://www.mongodb.com",
    sector: "database",
    stage: "public",
    what: "Document-oriented database with a multi-cloud Atlas service. Public org ships drivers across 12+ languages plus Compass, Realm, and the Mongoose ecosystem.",
    momentum: "steady",
    repos: "200+ public repos across drivers, tooling, and infra",
    lang: "C++ / Go / TypeScript",
    related: ["database", "developer-tools", "infrastructure"],
  }),
  build({
    slug: "datadog",
    name: "Datadog",
    githubOrg: "DataDog",
    homepage: "https://www.datadoghq.com",
    sector: "observability",
    stage: "public",
    what: "Cloud observability platform. Public org ships the Agent, integrations, and lambda layers across every major runtime. Consistent multi-language SDK release cadence.",
    momentum: "steady",
    repos: "300+ public repos",
    lang: "Go / Python",
    related: ["observability", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "elastic",
    name: "Elastic",
    githubOrg: "elastic",
    homepage: "https://www.elastic.co",
    sector: "observability",
    stage: "public",
    what: "Elasticsearch creators — search, observability, and security stack. Massive public OSS surface across Elasticsearch, Kibana, Logstash, Beats, and the Elastic Common Schema.",
    momentum: "steady",
    repos: "300+ public repos across the entire stack",
    lang: "Java / TypeScript / Go",
    related: ["observability", "database", "infrastructure"],
  }),
  build({
    slug: "clickhouse",
    name: "ClickHouse",
    githubOrg: "ClickHouse",
    homepage: "https://clickhouse.com",
    sector: "database",
    stage: "series-c",
    what: "Real-time analytics database. The core engine is fully open-source with active enterprise development on cloud, replication, and the SQL layer.",
    momentum: "accelerating",
    repos: "50+ active public repos",
    lang: "C++ / Rust",
    related: ["database", "analytics", "infrastructure"],
  }),
  build({
    slug: "temporal",
    name: "Temporal",
    githubOrg: "temporalio",
    homepage: "https://temporal.io",
    sector: "developer-tools",
    stage: "series-c",
    what: "Durable workflow orchestration platform. Core Go server, multi-language SDKs (TS/Py/Java/Go/.NET/Ruby/PHP), and visibility primitives all public.",
    momentum: "accelerating",
    repos: "100+ public repos across server, SDKs, and tooling",
    lang: "Go / TypeScript / Python",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "pulumi",
    name: "Pulumi",
    githubOrg: "pulumi",
    homepage: "https://www.pulumi.com",
    sector: "developer-tools",
    stage: "series-c",
    what: "Infrastructure-as-code as actual code — TypeScript, Python, Go, .NET, Java IaC. The cloud-native challenger to Terraform; growing post-HashiCorp acquisition.",
    momentum: "accelerating",
    repos: "200+ public repos across providers and SDKs",
    lang: "Go / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "figma",
    name: "Figma",
    githubOrg: "figma",
    homepage: "https://www.figma.com",
    sector: "productivity",
    stage: "later",
    what: "Collaborative design platform. Public org hosts design-system tooling, the Plugin API, and devtools. Core product is closed but the developer surface is meaningful.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript / Rust",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "plaid",
    name: "Plaid",
    githubOrg: "plaid",
    homepage: "https://plaid.com",
    sector: "fintech",
    stage: "later",
    what: "Banking API platform. Public org hosts SDKs across 10+ languages plus the Link integration kits — the developer surface of US fintech.",
    momentum: "steady",
    repos: "50+ public repos across SDKs and templates",
    lang: "Go / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "twilio",
    name: "Twilio",
    githubOrg: "twilio",
    homepage: "https://www.twilio.com",
    sector: "developer-tools",
    stage: "public",
    what: "Communications API platform. Public org with SDKs across 8+ languages plus Functions, Studio tooling, and the SendGrid+Segment integration surface.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Go / TypeScript / Python",
    related: ["developer-tools", "fintech"],
  }),
  build({
    slug: "netlify",
    name: "Netlify",
    githubOrg: "netlify",
    homepage: "https://www.netlify.com",
    sector: "infrastructure",
    stage: "later",
    what: "Jamstack hosting and edge platform. Public org hosts CLI, build plugins, edge-functions tooling, and the Netlify Identity service.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "sourcegraph",
    name: "Sourcegraph",
    githubOrg: "sourcegraph",
    homepage: "https://sourcegraph.com",
    sector: "developer-tools",
    stage: "later",
    what: "Code intelligence platform with the Cody AI coding assistant. Public org hosts the indexer, language servers, and Cody extensions across major IDEs.",
    momentum: "accelerating",
    repos: "100+ public repos",
    lang: "Go / TypeScript",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "dbt-labs",
    name: "dbt Labs",
    githubOrg: "dbt-labs",
    homepage: "https://www.getdbt.com",
    sector: "analytics",
    stage: "later",
    what: "Analytics engineering tooling. dbt is the de-facto SQL transformation layer for Snowflake, BigQuery, Databricks, and modern Postgres warehouses.",
    momentum: "steady",
    repos: "100+ public repos across adapters and packages",
    lang: "Python / SQL",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "duckdb",
    name: "DuckDB",
    githubOrg: "duckdb",
    homepage: "https://duckdb.org",
    sector: "database",
    stage: "seed",
    what: "In-process analytical database engine. The DuckDB core ships under MIT license with bindings in 10+ languages — the SQLite of analytics.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "C++ / Rust",
    related: ["database", "analytics"],
  }),
  build({
    slug: "honeycomb",
    name: "Honeycomb",
    githubOrg: "honeycombio",
    homepage: "https://www.honeycomb.io",
    sector: "observability",
    stage: "later",
    what: "Observability platform optimized for high-cardinality traces. Public org hosts agents, integrations, OpenTelemetry collectors, and Honeycomb-Lambda layers.",
    momentum: "steady",
    repos: "80+ public repos",
    lang: "Go / TypeScript",
    related: ["observability", "infrastructure"],
  }),
  build({
    slug: "adyen",
    name: "Adyen",
    githubOrg: "Adyen",
    homepage: "https://www.adyen.com",
    sector: "fintech",
    stage: "public",
    what: "European-anchored payments platform. Public org hosts API libraries plus the iDEAL, Klarna, and POS integration tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Java / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  // ───────────────────────── 2026-05-28 expansion 2 (20 orgs) ─────────────────────────
  build({
    slug: "redis",
    name: "Redis",
    githubOrg: "redis",
    homepage: "https://redis.io",
    sector: "database",
    stage: "later",
    what: "In-memory data store and broker. Redis is the de-facto cache layer of modern apps; the public org hosts the core engine plus 12+ client libraries.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "C / Go",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "mariadb",
    name: "MariaDB",
    githubOrg: "MariaDB",
    homepage: "https://mariadb.com",
    sector: "database",
    stage: "public",
    what: "MySQL fork run by the original MySQL team. Open-source relational database with enterprise replication, ColumnStore, and SkySQL cloud tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "C / C++",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "couchbase",
    name: "Couchbase",
    githubOrg: "couchbase",
    homepage: "https://www.couchbase.com",
    sector: "database",
    stage: "public",
    what: "JSON document database with SQL++. Public org hosts the core server, mobile sync, and 10+ SDK languages.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "C++ / Go",
    related: ["database", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "timescale",
    name: "Timescale",
    githubOrg: "timescale",
    homepage: "https://www.timescale.com",
    sector: "database",
    stage: "series-c",
    what: "Postgres extension for time-series data plus a hosted cloud. The TimescaleDB engine ships under Timescale License; SDKs and tooling are MIT.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "C / Go",
    related: ["database", "analytics"],
  }),
  build({
    slug: "meilisearch",
    name: "Meilisearch",
    githubOrg: "meilisearch",
    homepage: "https://www.meilisearch.com",
    sector: "database",
    stage: "series-b",
    what: "Lightweight Rust-native search engine. Open-source core with a hosted cloud — the developer-experience-first alternative to Elasticsearch for app search.",
    momentum: "accelerating",
    repos: "50+ public repos",
    lang: "Rust / TypeScript",
    related: ["database", "developer-tools"],
  }),
  build({
    slug: "typesense",
    name: "Typesense",
    githubOrg: "typesense",
    homepage: "https://typesense.org",
    sector: "database",
    stage: "seed",
    what: "C++ open-source search engine designed as a Meilisearch / Elasticsearch alternative. Hosted Typesense Cloud is the commercial path.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "C++ / TypeScript",
    related: ["database", "developer-tools"],
  }),
  build({
    slug: "weaviate",
    name: "Weaviate",
    githubOrg: "weaviate",
    homepage: "https://weaviate.io",
    sector: "database",
    stage: "series-b",
    what: "Open-source vector database with hybrid search. One of the headline players in the AI-native data layer.",
    momentum: "accelerating",
    repos: "50+ public repos",
    lang: "Go / Python",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "qdrant",
    name: "Qdrant",
    githubOrg: "qdrant",
    homepage: "https://qdrant.tech",
    sector: "database",
    stage: "series-a",
    what: "Rust-native vector database with HNSW indexing. Open-source core plus Qdrant Cloud; widely used in RAG production stacks.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / Python",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "milvus",
    name: "Milvus",
    githubOrg: "milvus-io",
    homepage: "https://milvus.io",
    sector: "database",
    stage: "series-b",
    what: "Open-source distributed vector database from Zilliz. The most-starred open-source vector DB; multi-language SDKs across Python, Go, Java, Node.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "Go / C++",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "bun",
    name: "Bun",
    githubOrg: "oven-sh",
    homepage: "https://bun.sh",
    sector: "developer-tools",
    stage: "series-b",
    what: "All-in-one JavaScript runtime, package manager, bundler, and test runner. Written in Zig with custom JSC integration; one of the most active OSS JS projects.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Zig / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "deno",
    name: "Deno",
    githubOrg: "denoland",
    homepage: "https://deno.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "Secure JavaScript and TypeScript runtime by Ryan Dahl, plus Deno Deploy edge runtime and Deno KV. Rust-based engine with V8.",
    momentum: "accelerating",
    repos: "50+ public repos",
    lang: "Rust / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "amplitude",
    name: "Amplitude",
    githubOrg: "amplitude",
    homepage: "https://amplitude.com",
    sector: "analytics",
    stage: "public",
    what: "Product analytics platform. Public org hosts analytics SDKs across web, iOS, Android, plus the Experiment feature-flag tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Swift / Kotlin",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "mixpanel",
    name: "Mixpanel",
    githubOrg: "mixpanel",
    homepage: "https://mixpanel.com",
    sector: "analytics",
    stage: "later",
    what: "Product analytics platform. Public org hosts SDKs across 12+ platforms plus the JQL exploratory query tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Python / Swift",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "metabase",
    name: "Metabase",
    githubOrg: "metabase",
    homepage: "https://www.metabase.com",
    sector: "analytics",
    stage: "series-c",
    what: "Open-source BI tool. Clojure backend with React frontend; widely adopted at SMB and mid-market for self-serve analytics.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Clojure / TypeScript",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "runway",
    name: "Runway ML",
    githubOrg: "runwayml",
    homepage: "https://runwayml.com",
    sector: "ai-ml",
    stage: "later",
    what: "Generative video and image platform. The category-defining AI video tool with proprietary Gen-* model family; limited public ML surface but active SDK presence.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "creative-tools"],
  }),
  build({
    slug: "stability-ai",
    name: "Stability AI",
    githubOrg: "Stability-AI",
    homepage: "https://stability.ai",
    sector: "ai-ml",
    stage: "series-c",
    what: "Open-weight model lab known for Stable Diffusion. Public org hosts model code, training recipes, and the StableLM language-model family.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python",
    related: ["ai-ml", "creative-tools"],
  }),
  build({
    slug: "ai21-labs",
    name: "AI21 Labs",
    githubOrg: "AI21Labs",
    homepage: "https://www.ai21.com",
    sector: "ai-ml",
    stage: "series-c",
    what: "Israeli frontier-AI lab. Builds the Jamba and Jurassic model families with strong reasoning and long-context focus. SDK + API tooling public.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml"],
  }),
  build({
    slug: "pinecone",
    name: "Pinecone",
    githubOrg: "pinecone-io",
    homepage: "https://www.pinecone.io",
    sector: "database",
    stage: "series-b",
    what: "Managed vector database optimized for retrieval-augmented generation. Proprietary engine with public SDKs and integration tooling.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python / TypeScript",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "writer",
    name: "Writer",
    githubOrg: "writer",
    homepage: "https://writer.com",
    sector: "ai-ml",
    stage: "series-c",
    what: "Enterprise generative AI platform with the Palmyra model family. Focus on regulated industries with on-prem deployment options.",
    momentum: "steady",
    repos: "15+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "productivity"],
  }),
  build({
    slug: "weights-biases",
    name: "Weights & Biases",
    githubOrg: "wandb",
    homepage: "https://wandb.ai",
    sector: "developer-tools",
    stage: "series-c",
    what: "ML experiment tracking, model registry, and evaluation platform. Public org hosts the wandb SDK, Weave LLM observability layer, and Launch.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Python / TypeScript",
    related: ["developer-tools", "ai-ml", "observability"],
  }),
  // ───────────────────────── 2026-05-28 expansion 3 (15 orgs — cross 1000) ─────────────────────────
  build({
    slug: "cockroachdb",
    name: "CockroachDB",
    githubOrg: "cockroachdb",
    homepage: "https://www.cockroachlabs.com",
    sector: "database",
    stage: "later",
    what: "Distributed SQL database from Cockroach Labs. Strong PostgreSQL compatibility, global low-latency replication, serverless tier. Founded by ex-Google Spanner engineers.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Go",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "influxdata",
    name: "InfluxData",
    githubOrg: "influxdata",
    homepage: "https://www.influxdata.com",
    sector: "database",
    stage: "later",
    what: "Time-series database platform with InfluxDB OSS, Cloud, and Enterprise tiers. Major IoT and observability data layer; recently shifted core engine to Rust.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Go / Rust",
    related: ["database", "observability", "infrastructure"],
  }),
  build({
    slug: "dremio",
    name: "Dremio",
    githubOrg: "dremio",
    homepage: "https://www.dremio.com",
    sector: "database",
    stage: "later",
    what: "Open lakehouse platform built on Apache Iceberg and Apache Arrow. Query engine on top of cloud data lakes with strong SQL semantics.",
    momentum: "steady",
    repos: "80+ public repos",
    lang: "Java / TypeScript",
    related: ["database", "analytics"],
  }),
  build({
    slug: "astro",
    name: "Astro",
    githubOrg: "withastro",
    homepage: "https://astro.build",
    sector: "developer-tools",
    stage: "series-a",
    what: "Multi-framework static site generator with islands architecture. Strong content-site focus competing with Next.js for content-heavy use cases.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["developer-tools"],
  }),
  build({
    slug: "nuxt",
    name: "Nuxt (NuxtLabs)",
    githubOrg: "nuxt",
    homepage: "https://nuxt.com",
    sector: "developer-tools",
    stage: "seed",
    what: "Vue.js meta-framework plus commercial team (NuxtLabs). Stripe-style developer surface for the Vue ecosystem with strong SSR and edge-runtime story.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "TypeScript",
    related: ["developer-tools"],
  }),
  build({
    slug: "tauri",
    name: "Tauri (CrabNebula)",
    githubOrg: "tauri-apps",
    homepage: "https://tauri.app",
    sector: "developer-tools",
    stage: "seed",
    what: "Rust-based desktop app framework competing with Electron. Smaller binary, better performance, native OS bindings. CrabNebula is the commercial team.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "ory",
    name: "Ory",
    githubOrg: "ory",
    homepage: "https://www.ory.sh",
    sector: "developer-tools",
    stage: "series-a",
    what: "Open-source identity infrastructure — Kratos (identity), Hydra (OAuth2), Keto (authorization), Oathkeeper (zero trust). Self-hostable Auth0 alternative.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Go / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "kong",
    name: "Kong",
    githubOrg: "Kong",
    homepage: "https://konghq.com",
    sector: "infrastructure",
    stage: "later",
    what: "API gateway and microservices management platform. Kong Gateway is OSS (Lua + nginx); Kong Konnect is the commercial cloud. Strong AI Gateway momentum in 2025-2026.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Lua / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "langfuse",
    name: "Langfuse",
    githubOrg: "langfuse",
    homepage: "https://langfuse.com",
    sector: "observability",
    stage: "seed",
    what: "LLM observability and evaluation platform. Open-source core plus cloud. Strong RAG and agent-trace use cases; rapid adoption in 2025-2026 agent-infra stacks.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript / Python",
    related: ["observability", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "arize-ai",
    name: "Arize AI",
    githubOrg: "Arize-ai",
    homepage: "https://arize.com",
    sector: "observability",
    stage: "series-b",
    what: "ML observability platform with strong LLM evaluation focus. Phoenix is their open-source LLM tracing tool; commercial cloud handles enterprise-scale eval workflows.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["observability", "ai-ml"],
  }),
  build({
    slug: "braintrust",
    name: "Braintrust",
    githubOrg: "braintrustdata",
    homepage: "https://www.braintrust.dev",
    sector: "observability",
    stage: "series-a",
    what: "LLM eval and observability platform with 'evals as code' philosophy. Competes with Helicone, Langfuse, and Arize on the LLM-app observability frontier.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript",
    related: ["observability", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "helicone",
    name: "Helicone",
    githubOrg: "Helicone",
    homepage: "https://www.helicone.ai",
    sector: "observability",
    stage: "seed",
    what: "LLM observability proxy plus dashboard. Drop-in OpenAI-API-compatible proxy that logs every request; YC-backed with strong indie-developer adoption.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript",
    related: ["observability", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "voyage-ai",
    name: "Voyage AI",
    githubOrg: "voyage-ai",
    homepage: "https://www.voyageai.com",
    sector: "ai-ml",
    stage: "seed",
    what: "Embedding-model specialist focused on retrieval-augmented generation accuracy. Acquired by MongoDB in early 2025 as their RAG/embedding stack.",
    momentum: "steady",
    repos: "10+ public repos",
    lang: "Python",
    related: ["ai-ml", "database"],
  }),
  build({
    slug: "jina-ai",
    name: "Jina AI",
    githubOrg: "jina-ai",
    homepage: "https://jina.ai",
    sector: "ai-ml",
    stage: "series-a",
    what: "Open-source neural search and embedding infrastructure. Builds Jina (multi-modal AI framework), CLIP embeddings, and reranker models for the search stack.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python",
    related: ["ai-ml", "database", "developer-tools"],
  }),
  build({
    slug: "backstage",
    name: "Backstage (Spotify)",
    githubOrg: "backstage",
    homepage: "https://backstage.io",
    sector: "developer-tools",
    stage: "later",
    what: "Developer portal platform for managing services, docs, and tooling. Open-sourced by Spotify in 2020; now a CNCF incubating project with broad enterprise adoption.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "infrastructure", "productivity"],
  }),
  // ───────────────────────── 2026-05-29 expansion 4 (15 orgs — fintech/analytics/prod gaps) ─────────────────────────
  build({
    slug: "wise",
    name: "Wise",
    githubOrg: "transferwise",
    homepage: "https://wise.com",
    sector: "fintech",
    stage: "public",
    what: "Cross-border payments platform (formerly TransferWise). Strong public engineering footprint with comprehensive SDK and integration tooling across multiple languages.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Java / Kotlin",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "nubank",
    name: "Nubank",
    githubOrg: "nubank",
    homepage: "https://nubank.com.br",
    sector: "fintech",
    stage: "public",
    what: "Brazilian neobank and the largest digital bank in Latin America. Public engineering presence anchored around Clojure tooling and microservices infrastructure.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Clojure / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "monzo",
    name: "Monzo",
    githubOrg: "monzo",
    homepage: "https://monzo.com",
    sector: "fintech",
    stage: "later",
    what: "UK neobank known for engineering blog culture and microservices-heavy architecture. Public org hosts open-source tooling around Cassandra, gRPC, and Kubernetes operations.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "Go / Python",
    related: ["fintech", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "n26",
    name: "N26",
    githubOrg: "n26",
    homepage: "https://n26.com",
    sector: "fintech",
    stage: "later",
    what: "German digital bank serving multiple European markets. Public org hosts SDK tooling and architectural primitives around their pan-European banking infrastructure.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Kotlin / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "fivetran",
    name: "Fivetran",
    githubOrg: "fivetran",
    homepage: "https://www.fivetran.com",
    sector: "analytics",
    stage: "later",
    what: "Automated ELT data pipeline platform connecting hundreds of SaaS sources to data warehouses. Public org hosts connector SDKs, dbt integration, and customer-extension tooling.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "Java / TypeScript",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "airbyte",
    name: "Airbyte",
    githubOrg: "airbytehq",
    homepage: "https://airbyte.com",
    sector: "analytics",
    stage: "series-b",
    what: "Open-source data integration platform with 350+ connectors. The OSS challenger to Fivetran with strong community-built connector momentum.",
    momentum: "accelerating",
    repos: "100+ public repos",
    lang: "Python / Java",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "cube",
    name: "Cube",
    githubOrg: "cube-js",
    homepage: "https://cube.dev",
    sector: "analytics",
    stage: "series-b",
    what: "Semantic layer and headless BI platform. Open-source core (Cube.js) plus Cube Cloud. Strong adoption for embedded analytics and AI-grounded BI use cases in 2025-2026.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / TypeScript",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "preset",
    name: "Preset",
    githubOrg: "preset-io",
    homepage: "https://preset.io",
    sector: "analytics",
    stage: "series-b",
    what: "Managed Apache Superset platform. Commercial vendor for the open-source Superset BI tool, founded by the original Superset creator (Maxime Beauchemin).",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python / TypeScript",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "hex",
    name: "Hex",
    githubOrg: "hex-inc",
    homepage: "https://hex.tech",
    sector: "analytics",
    stage: "series-c",
    what: "Collaborative data workspace combining notebooks, SQL, and BI dashboards. Strong adoption with modern data teams; AI-grounded analytics is a 2025-2026 product focus.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript / Python",
    related: ["analytics", "developer-tools", "productivity"],
  }),
  build({
    slug: "retool",
    name: "Retool",
    githubOrg: "tryretool",
    homepage: "https://retool.com",
    sector: "productivity",
    stage: "series-c",
    what: "Internal tools platform — drag-and-drop interface builder backed by SQL, REST, and GraphQL. Strong adoption with engineering and ops teams for replacing custom internal dashboards.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "coda",
    name: "Coda",
    githubOrg: "coda-io",
    homepage: "https://coda.io",
    sector: "productivity",
    stage: "later",
    what: "Document-and-database hybrid productivity platform competing with Notion. Public org hosts the Coda Packs SDK for third-party integrations.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "miro",
    name: "Miro",
    githubOrg: "miroapp",
    homepage: "https://miro.com",
    sector: "productivity",
    stage: "later",
    what: "Collaborative whiteboard platform widely adopted for design workshops, sprint planning, and remote-team workflows. Public org hosts Web SDK and app marketplace tooling.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "monday",
    name: "Monday.com",
    githubOrg: "monday-com",
    homepage: "https://monday.com",
    sector: "productivity",
    stage: "public",
    what: "Work management platform with strong customization and integration depth. Public org hosts apps SDK, GraphQL tooling, and integration primitives for the Monday Apps Marketplace.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "TypeScript / Ruby",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "asana",
    name: "Asana",
    githubOrg: "Asana",
    homepage: "https://asana.com",
    sector: "productivity",
    stage: "public",
    what: "Work management platform with strong API ecosystem. Public org hosts SDK clients across major languages plus the Luna React framework that powers their web app.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Python",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "zapier",
    name: "Zapier",
    githubOrg: "zapier",
    homepage: "https://zapier.com",
    sector: "productivity",
    stage: "later",
    what: "No-code automation platform connecting 7,000+ apps. Public org hosts the Zapier Platform CLI, app templates, and connector developer tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Python",
    related: ["productivity", "developer-tools"],
  }),
];

export function getCompany(slug: string): Company | undefined {
  return companies.find((c) => c.slug === slug);
}

export function getAllCompanySlugs(): string[] {
  return companies.map((c) => c.slug);
}
