/**
 * /signal/[slug] entity pages — per-company GitHub engineering signal reports.
 *
 * Seed corpus of public, well-known startups and scale-ups that maintain a
 * visible GitHub org. Each entry powers one /signal/{slug} page with
 * Organization JSON-LD, BreadcrumbList, FAQPage, and a CTA into /firstlook.
 *
 * Privacy posture: only companies whose engineering operations are already
 * matter-of-fact public (the company self-publishes its GitHub org on its
 * homepage, devrel blog, or hiring page). No private orgs, no leaked
 * employee data, no inferred-from-LinkedIn personal data — only signals
 * derivable from public GitHub events.
 *
 * Signal scores are static placeholders for the v1 ship; a follow-up PR
 * will join these slugs against lib/data.ts and the weekly Top 100 to
 * populate live numbers. The page renders identically either way.
 */

export interface CompanyFAQ {
  question: string;
  answer: string;
}

export interface Company {
  slug: string;
  name: string;
  githubOrg: string;
  homepageUrl: string;
  sector: string;
  stage: "seed" | "series-a" | "series-b" | "series-c" | "later" | "public";
  description: string;
  // SEO surfaces
  title: string;
  metaDescription: string;
  h1: string;
  tagline: string;
  intro: string;
  signalSummary: string;
  whatWeTrack: string;
  whyItMatters: string;
  // Editorially curated snapshot — NOT a live measurement. See
  // REFERENCE_PROFILE_REVIEWED below and the honesty note on build().
  publicSignal: {
    momentum: "accelerating" | "steady" | "decelerating" | "unranked";
    publicReposEstimate: string;
    languageBias: string;
  };
  faqs: CompanyFAQ[];
  relatedSectors: string[];
}

/**
 * Date this reference corpus was last editorially reviewed.
 *
 * HONESTY CONTRACT (2026-07-25): the `publicSignal` figures below
 * (momentum / repos / language bias) are hand-curated editorial values, not
 * live GitHub aggregates — there is no join, and only 11 of these 165
 * companies appear in the tracked panel at all. Copy on these pages must
 * therefore never claim the numbers are measured, refreshed weekly, or that
 * the site "monitors" the company. It previously did claim exactly that
 * ("Updated weekly from public GitHub events"), which was false on all 165
 * live pages. If you add or edit an entry, keep the framing as a curated
 * benchmark profile and bump this date.
 *
 * Live, genuinely measured data lives on /weekly/top-100 and /startup/[slug],
 * which are driven by data/top-100/*.json and data/startups.json.
 */
export const REFERENCE_PROFILE_REVIEWED = "2026-07-25";

// Concise content generator — each entry overrides only the fields that
// differ. Keeps the seed corpus tight while ensuring every page has
// unique title, description, intro, and FAQs.
function build(c: {
  slug: string;
  name: string;
  githubOrg: string;
  homepage: string;
  sector: string;
  stage: Company["stage"];
  what: string;
  momentum: Company["publicSignal"]["momentum"];
  repos: string;
  lang: string;
  related: string[];
}): Company {
  const stageLabel = c.stage === "public" ? "public" : `${c.stage.replace("-", " ")}`;
  return {
    slug: c.slug,
    name: c.name,
    githubOrg: c.githubOrg,
    homepageUrl: c.homepage,
    sector: c.sector,
    stage: c.stage,
    description: `${c.name} (${c.sector}, ${stageLabel}) — GitHub org github.com/${c.githubOrg}. ${c.what}`,
    // No brand suffix here — app/layout.tsx applies the title template
    // "%s | VC Deal Flow Signal". Hardcoding it doubled the brand in <title>.
    title: `${c.name} GitHub Engineering Signals (2026)`,
    metaDescription: `${c.name} public GitHub engineering profile — sector, stage, repo footprint, and language bias, curated as a ${c.sector} benchmark for investors and operators. Reference profile, reviewed ${REFERENCE_PROFILE_REVIEWED}.`,
    h1: `${c.name} GitHub Engineering Signals`,
    tagline: `A quantitative view of ${c.name}'s public engineering activity — what we track and why investors watch it.`,
    intro: `${c.name} (${c.sector}, ${stageLabel}) is a public technical company VC Deal Flow Signal profiles as a ${c.sector} benchmark, via the public github.com/${c.githubOrg} org. ${c.what} Investors who source deals in ${c.sector} often watch ${c.name} as a reference point — the kind of commit velocity, contributor influx, and infrastructure repo growth that established players sustain is the curve early-stage companies get measured against.`,
    signalSummary: `${c.name}: momentum ${c.momentum}, ${c.repos}, ${c.lang}. Curated benchmark figures reviewed ${REFERENCE_PROFILE_REVIEWED} — not a live measurement.`,
    whatWeTrack: `Profiled through the same six-signal lens applied to the tracked panel — commit velocity, contributor influx, repo-creation pulse, language shifts, issue cadence. Definitions: /methodology.`,
    whyItMatters: `${c.what} That makes ${c.name} a useful ${c.sector} reference line: the interesting names are the early-stage orgs whose acceleration now resembles this one's 12-18 months ago. Those are on the tracked panel at /weekly/top-100.`,
    publicSignal: {
      momentum: c.momentum,
      publicReposEstimate: c.repos,
      languageBias: c.lang,
    },
    faqs: [
      {
        question: `What data does VC Deal Flow Signal collect about ${c.name}?`,
        answer: `Only public GitHub events: commits, PRs, issues, releases, and contributor activity from github.com/${c.githubOrg}. We do not collect employee personal data, private repo content, or any signal that is not already publicly visible on GitHub.com. This page is generated from public-events aggregations.`,
      },
      {
        question: `Is this a live measurement of ${c.name}?`,
        answer: `No. The momentum, repo-footprint, and language figures are editorially curated benchmark values, last reviewed ${REFERENCE_PROFILE_REVIEWED} — they do not refresh automatically. Live, weekly-measured signal data covers the tracked startup panel instead: /weekly/top-100. Not investment advice, not an endorsement; ${c.name} has not paid for placement and is not affiliated with VC Deal Flow Signal.`,
      },
    ],
    relatedSectors: c.related,
  };
}

export const companies: Company[] = [
  build({
    slug: "vercel",
    name: "Vercel",
    githubOrg: "vercel",
    homepage: "https://vercel.com",
    sector: "developer-tools",
    stage: "later",
    what: "Vercel ships the frontend cloud (Next.js, hosting, AI SDK, AI Gateway, Workflow, Sandbox). Their public org is one of the most active in the developer-tools sector.",
    momentum: "accelerating",
    repos: "300+ active public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "ai-ml", "infrastructure"],
  }),
  build({
    slug: "supabase",
    name: "Supabase",
    githubOrg: "supabase",
    homepage: "https://supabase.com",
    sector: "developer-tools",
    stage: "series-c",
    what: "Open-source Firebase alternative — Postgres-native backend, auth, storage, edge functions. Their commit velocity has compounded steadily since the 2020 launch.",
    momentum: "accelerating",
    repos: "200+ active public repos",
    lang: "TypeScript / Go",
    related: ["developer-tools", "database", "infrastructure"],
  }),
  build({
    slug: "resend",
    name: "Resend",
    githubOrg: "resend",
    homepage: "https://resend.com",
    sector: "developer-tools",
    stage: "series-a",
    what: "Email API for developers. SDKs across every major runtime; React Email is the de facto template library. A textbook case of API-first developer-tools growth.",
    momentum: "accelerating",
    repos: "60+ active public repos",
    lang: "TypeScript",
    related: ["developer-tools", "api-platforms"],
  }),
  build({
    slug: "posthog",
    name: "PostHog",
    githubOrg: "PostHog",
    homepage: "https://posthog.com",
    sector: "analytics",
    stage: "series-c",
    what: "Open-source product analytics — events, session replay, feature flags, A/B tests, LLM observability, all in one self-hostable platform.",
    momentum: "accelerating",
    repos: "100+ active public repos",
    lang: "Python / TypeScript",
    related: ["analytics", "developer-tools", "ai-ml"],
  }),
  build({
    slug: "linear",
    name: "Linear",
    githubOrg: "linear",
    homepage: "https://linear.app",
    sector: "productivity",
    stage: "series-c",
    what: "Issue tracking and product management for software teams. Their public SDK and API ecosystem ship steady weekly updates.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "convex",
    name: "Convex",
    githubOrg: "get-convex",
    homepage: "https://convex.dev",
    sector: "database",
    stage: "series-b",
    what: "Reactive backend platform — database, queries, mutations, file storage, scheduling, all in one TypeScript-native runtime.",
    momentum: "accelerating",
    repos: "50+ active public repos",
    lang: "TypeScript / Rust",
    related: ["database", "developer-tools", "ai-ml"],
  }),
  build({
    slug: "neon",
    name: "Neon",
    githubOrg: "neondatabase",
    homepage: "https://neon.tech",
    sector: "database",
    stage: "series-c",
    what: "Serverless Postgres with branching. The standard managed Postgres choice for AI-era developer-tools companies.",
    momentum: "accelerating",
    repos: "40+ active public repos",
    lang: "Rust / TypeScript",
    related: ["database", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "modal",
    name: "Modal",
    githubOrg: "modal-labs",
    homepage: "https://modal.com",
    sector: "ai-infra",
    stage: "series-b",
    what: "Serverless compute for AI — train, fine-tune, serve, and orchestrate Python workloads with sub-second cold starts on GPUs.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Python",
    related: ["ai-ml", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "replicate",
    name: "Replicate",
    githubOrg: "replicate",
    homepage: "https://replicate.com",
    sector: "ai-infra",
    stage: "series-b",
    what: "Run open-source ML models with an API. Their Cog runtime is one of the most-forked packaging standards in OSS ML.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "Python / Go",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "anthropic",
    name: "Anthropic",
    githubOrg: "anthropics",
    homepage: "https://www.anthropic.com",
    sector: "ai-ml",
    stage: "later",
    what: "Frontier AI lab — Claude model family, MCP protocol, Claude Code CLI, Claude Agent SDK. Their MCP standardization is reshaping the entire agentic ecosystem.",
    momentum: "accelerating",
    repos: "30+ active public repos",
    lang: "TypeScript / Python",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "openai",
    name: "OpenAI",
    githubOrg: "openai",
    homepage: "https://openai.com",
    sector: "ai-ml",
    stage: "later",
    what: "Closed-weight frontier lab whose open-source presence (SDKs, gym, whisper, evals) defines the public surface area for AI infrastructure.",
    momentum: "steady",
    repos: "100+ public repos (legacy + active)",
    lang: "Python / TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "mistral-ai",
    name: "Mistral AI",
    githubOrg: "mistralai",
    homepage: "https://mistral.ai",
    sector: "ai-ml",
    stage: "series-b",
    what: "Open-weight European frontier lab. Their public Mistral and Mixtral checkpoints are a benchmark for permissive-license LLM releases.",
    momentum: "accelerating",
    repos: "15+ active public repos",
    lang: "Python",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "cohere",
    name: "Cohere",
    githubOrg: "cohere-ai",
    homepage: "https://cohere.com",
    sector: "ai-ml",
    stage: "series-c",
    what: "Enterprise-focused LLM provider — strong retrieval and embeddings stack, growing agent and tool-use layer.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "huggingface",
    name: "Hugging Face",
    githubOrg: "huggingface",
    homepage: "https://huggingface.co",
    sector: "ai-ml",
    stage: "later",
    what: "The default model hub for open-weight AI. Transformers, datasets, diffusers, accelerate — the entire OSS ML stack ships through this org.",
    // Downgraded 2026-05-30: current-period (q2-2026) public commit velocity -49%.
    momentum: "steady",
    repos: "300+ active public repos",
    lang: "Python / Rust",
    related: ["ai-ml", "developer-tools", "infrastructure"],
  }),
  build({
    slug: "stripe",
    name: "Stripe",
    githubOrg: "stripe",
    homepage: "https://stripe.com",
    sector: "fintech",
    stage: "later",
    what: "Payments infrastructure. Their public SDK org is a long-running baseline of what a mature, multi-language, API-first engineering organization looks like.",
    momentum: "steady",
    repos: "200+ public repos across language SDKs",
    lang: "Ruby / Go / TypeScript",
    related: ["fintech", "developer-tools", "api-platforms"],
  }),
  build({
    slug: "cloudflare",
    name: "Cloudflare",
    githubOrg: "cloudflare",
    homepage: "https://www.cloudflare.com",
    sector: "infrastructure",
    stage: "public",
    what: "Edge platform — Workers, R2, D1, Hyperdrive, Durable Objects, AI Gateway. Their public org ships dozens of active repos across runtimes.",
    momentum: "accelerating",
    repos: "500+ active public repos",
    lang: "Rust / TypeScript",
    related: ["infrastructure", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "hashicorp",
    name: "HashiCorp",
    githubOrg: "hashicorp",
    homepage: "https://www.hashicorp.com",
    sector: "infrastructure",
    stage: "public",
    what: "Terraform, Vault, Consul, Nomad — the canonical infrastructure-as-code stack. Their public org is a long-running benchmark for OSS infra companies.",
    momentum: "steady",
    repos: "400+ public repos",
    lang: "Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "grafana",
    name: "Grafana Labs",
    githubOrg: "grafana",
    homepage: "https://grafana.com",
    sector: "observability",
    stage: "later",
    what: "Open-source observability — Grafana, Loki, Tempo, Mimir, Pyroscope. Their public org is one of the most active in monitoring tooling.",
    momentum: "accelerating",
    repos: "300+ public repos",
    lang: "Go / TypeScript",
    related: ["observability", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "sentry",
    name: "Sentry",
    githubOrg: "getsentry",
    homepage: "https://sentry.io",
    sector: "observability",
    stage: "later",
    what: "Open-source error monitoring and performance. Multi-language SDKs and the OSS Sentry server make this one of the most fork-able observability orgs.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Python / TypeScript",
    related: ["observability", "developer-tools"],
  }),
  build({
    slug: "prisma",
    name: "Prisma",
    githubOrg: "prisma",
    homepage: "https://www.prisma.io",
    sector: "developer-tools",
    stage: "series-b",
    what: "TypeScript ORM and database tooling. Strong public SDK presence and steady release cadence over multiple years.",
    momentum: "steady",
    repos: "60+ public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "database"],
  }),
  build({
    slug: "drizzle",
    name: "Drizzle",
    githubOrg: "drizzle-team",
    homepage: "https://orm.drizzle.team",
    sector: "developer-tools",
    stage: "seed",
    what: "TypeScript-first ORM that became the default Drizzle replacement choice in the AI-era stack. Fast-compounding GitHub presence.",
    momentum: "accelerating",
    repos: "20+ active public repos",
    lang: "TypeScript",
    related: ["developer-tools", "database"],
  }),
  build({
    slug: "clerk",
    name: "Clerk",
    githubOrg: "clerk",
    homepage: "https://clerk.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "User management for modern apps — auth, organizations, billing. Strong React/Next.js integration and growing multi-framework SDKs.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "trigger-dev",
    name: "Trigger.dev",
    githubOrg: "triggerdotdev",
    homepage: "https://trigger.dev",
    sector: "developer-tools",
    stage: "series-a",
    what: "Background jobs and durable workflows for developers. Open-core with a self-hostable runtime.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "inngest",
    name: "Inngest",
    githubOrg: "inngest",
    homepage: "https://www.inngest.com",
    sector: "developer-tools",
    stage: "series-a",
    what: "Event-driven workflow engine with strong AI-agent orchestration support. Open-source SDKs across runtimes.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "TypeScript / Go",
    related: ["developer-tools", "ai-ml", "infrastructure"],
  }),
  build({
    slug: "browserbase",
    name: "Browserbase",
    githubOrg: "browserbase",
    homepage: "https://www.browserbase.com",
    sector: "ai-infra",
    stage: "series-a",
    what: "Headless browser infrastructure for AI agents. One of the canonical picks for agent runtimes needing browser execution.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["ai-ml", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "e2b",
    name: "E2B",
    githubOrg: "e2b-dev",
    homepage: "https://e2b.dev",
    sector: "ai-infra",
    stage: "seed",
    what: "Sandboxed code execution for AI agents. Strong developer mindshare in the agent-runtime category.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript / Python",
    related: ["ai-ml", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "fly-io",
    name: "Fly.io",
    githubOrg: "superfly",
    homepage: "https://fly.io",
    sector: "infrastructure",
    stage: "series-b",
    what: "Global app platform — micro-VMs near users, with a strong Postgres and durable-objects layer.",
    momentum: "steady",
    repos: "60+ public repos",
    lang: "Go / Elixir / Rust",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "railway",
    name: "Railway",
    githubOrg: "railwayapp",
    homepage: "https://railway.app",
    sector: "infrastructure",
    stage: "series-a",
    what: "Heroku-style deploy platform with a sharp UI and a growing public SDK presence.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "upstash",
    name: "Upstash",
    githubOrg: "upstash",
    homepage: "https://upstash.com",
    sector: "infrastructure",
    stage: "series-a",
    what: "Serverless Redis and Kafka. A frequent default storage choice in the Vercel marketplace + AI-era stack.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "database", "developer-tools"],
  }),
  build({
    slug: "turso",
    name: "Turso",
    githubOrg: "tursodatabase",
    homepage: "https://turso.tech",
    sector: "database",
    stage: "series-a",
    what: "Edge SQLite (libSQL fork) for global low-latency reads. Heavy OSS contributions to libSQL.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / TypeScript",
    related: ["database", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "planetscale",
    name: "PlanetScale",
    githubOrg: "planetscale",
    homepage: "https://planetscale.com",
    sector: "database",
    stage: "series-c",
    what: "Serverless MySQL on Vitess. Public SDK and CLI shipped from a steady, multi-language org.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Go / TypeScript",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "stytch",
    name: "Stytch",
    githubOrg: "stytchauth",
    homepage: "https://stytch.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "Auth API for B2B and consumer apps. Multi-runtime SDKs with steady release cadence.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript / Go",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "workos",
    name: "WorkOS",
    githubOrg: "workos",
    homepage: "https://workos.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "Enterprise SSO, directory sync, audit logs — the SOC2-ready APIs that B2B SaaS bolts on for compliance.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Go / Ruby",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "fermyon",
    name: "Fermyon",
    githubOrg: "fermyon",
    homepage: "https://www.fermyon.com",
    sector: "infrastructure",
    stage: "series-a",
    what: "Wasm-native serverless platform — the canonical bet on WebAssembly as the next compute runtime.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Rust",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "fireworks-ai",
    name: "Fireworks AI",
    githubOrg: "fw-ai",
    homepage: "https://fireworks.ai",
    sector: "ai-infra",
    stage: "series-b",
    what: "Fast inference for open-weight LLMs and image models. One of the rotating top picks for cost-per-token-served.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python / Rust",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "together-ai",
    name: "Together AI",
    githubOrg: "togethercomputer",
    homepage: "https://www.together.ai",
    sector: "ai-infra",
    stage: "series-b",
    what: "Open-weight LLM training and inference. Heavy public OSS presence — RedPajama, Mamba, OpenChatKit.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Python",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "groq",
    name: "Groq",
    githubOrg: "groq",
    homepage: "https://groq.com",
    sector: "ai-infra",
    stage: "series-c",
    what: "LPU-based fast inference. Strong developer mindshare for sub-100ms LLM responses.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "infrastructure"],
  }),
  build({
    slug: "dust-tt",
    name: "Dust",
    githubOrg: "dust-tt",
    homepage: "https://dust.tt",
    sector: "ai-ml",
    stage: "series-a",
    what: "AI-native workspace assistant for teams. Open-core platform with growing public agent surface area.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript / Rust",
    related: ["ai-ml", "productivity", "developer-tools"],
  }),
  build({
    slug: "cursor",
    name: "Cursor",
    githubOrg: "getcursor",
    homepage: "https://cursor.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "AI-first code editor that became the default IDE for AI-era engineers. Limited public surface but tracked closely by the sector.",
    momentum: "accelerating",
    repos: "5+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "lovable",
    name: "Lovable",
    githubOrg: "lovable-dev",
    homepage: "https://lovable.dev",
    sector: "ai-ml",
    stage: "series-a",
    what: "Vibe-coding platform — natural-language to full-stack web app. One of the most-discussed AI builder platforms of 2025-2026.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "remotion",
    name: "Remotion",
    githubOrg: "remotion-dev",
    homepage: "https://www.remotion.dev",
    sector: "developer-tools",
    stage: "series-a",
    what: "Programmatic video creation in React. The canonical pick for AI video pipelines and developer-built creative tools.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "ai-ml", "creative-tools"],
  }),
  build({
    slug: "tailwindcss",
    name: "Tailwind Labs",
    githubOrg: "tailwindlabs",
    homepage: "https://tailwindlabs.com",
    sector: "developer-tools",
    stage: "later",
    what: "Tailwind CSS, Headless UI, Heroicons. One of the longest-running and most influential public design-system orgs.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "design-systems"],
  }),
  build({
    slug: "shadcn",
    name: "shadcn",
    githubOrg: "shadcn-ui",
    homepage: "https://ui.shadcn.com",
    sector: "developer-tools",
    stage: "seed",
    what: "Component library by reference — copy-paste primitives that became the default React UI stack in 2024-2026.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "design-systems"],
  }),
  build({
    slug: "langchain",
    name: "LangChain",
    githubOrg: "langchain-ai",
    homepage: "https://www.langchain.com",
    sector: "ai-ml",
    stage: "series-b",
    what: "Most-forked AI-framework org — LangChain, LangGraph, LangSmith. Defines a large slice of the public agent-tooling surface.",
    // Downgraded 2026-05-30: current-period (q2-2026) public commit velocity -5% (flat after a strong run).
    momentum: "steady",
    repos: "60+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "crewai",
    name: "CrewAI",
    githubOrg: "crewAIInc",
    homepage: "https://www.crewai.com",
    sector: "ai-ml",
    stage: "seed",
    what: "Multi-agent orchestration framework with strong public mindshare in role-based agent design.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "letta-ai",
    name: "Letta",
    githubOrg: "letta-ai",
    homepage: "https://www.letta.com",
    sector: "ai-ml",
    stage: "seed",
    what: "Stateful agent framework (formerly MemGPT). The reference implementation for agent memory architectures.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "Python",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "mastra",
    name: "Mastra",
    githubOrg: "mastra-ai",
    homepage: "https://mastra.ai",
    sector: "ai-ml",
    stage: "seed",
    what: "TypeScript-first agent framework with strong workflow primitives. One of the fastest-rising agent libraries in late 2025.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["ai-ml", "developer-tools"],
  }),
  build({
    slug: "elevenlabs",
    name: "ElevenLabs",
    githubOrg: "elevenlabs",
    homepage: "https://elevenlabs.io",
    sector: "ai-ml",
    stage: "series-c",
    what: "Voice synthesis and audio AI. Public SDKs across runtimes with steady release cadence.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript / Python",
    related: ["ai-ml", "developer-tools", "creative-tools"],
  }),
  build({
    slug: "perplexity-ai",
    name: "Perplexity",
    githubOrg: "perplexity-ai",
    homepage: "https://www.perplexity.ai",
    sector: "ai-ml",
    stage: "series-c",
    what: "Answer engine with proprietary retrieval and ranking. Limited but precise public surface.",
    momentum: "accelerating",
    repos: "5+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "search"],
  }),
  // ───────────────────────── 2026-05-28 expansion (15 orgs) ─────────────────────────
  build({
    slug: "mongodb",
    name: "MongoDB",
    githubOrg: "mongodb",
    homepage: "https://www.mongodb.com",
    sector: "database",
    stage: "public",
    what: "Document-oriented database with a multi-cloud Atlas service. Public org ships drivers across 12+ languages plus Compass, Realm, and the Mongoose ecosystem.",
    momentum: "steady",
    repos: "200+ public repos across drivers, tooling, and infra",
    lang: "C++ / Go / TypeScript",
    related: ["database", "developer-tools", "infrastructure"],
  }),
  build({
    slug: "datadog",
    name: "Datadog",
    githubOrg: "DataDog",
    homepage: "https://www.datadoghq.com",
    sector: "observability",
    stage: "public",
    what: "Cloud observability platform. Public org ships the Agent, integrations, and lambda layers across every major runtime. Consistent multi-language SDK release cadence.",
    momentum: "steady",
    repos: "300+ public repos",
    lang: "Go / Python",
    related: ["observability", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "elastic",
    name: "Elastic",
    githubOrg: "elastic",
    homepage: "https://www.elastic.co",
    sector: "observability",
    stage: "public",
    what: "Elasticsearch creators — search, observability, and security stack. Massive public OSS surface across Elasticsearch, Kibana, Logstash, Beats, and the Elastic Common Schema.",
    momentum: "steady",
    repos: "300+ public repos across the entire stack",
    lang: "Java / TypeScript / Go",
    related: ["observability", "database", "infrastructure"],
  }),
  build({
    slug: "clickhouse",
    name: "ClickHouse",
    githubOrg: "ClickHouse",
    homepage: "https://clickhouse.com",
    sector: "database",
    stage: "series-c",
    what: "Real-time analytics database. The core engine is fully open-source with active enterprise development on cloud, replication, and the SQL layer.",
    // Downgraded 2026-05-30: current-period (q2-2026) public commit velocity -60%.
    momentum: "steady",
    repos: "50+ active public repos",
    lang: "C++ / Rust",
    related: ["database", "analytics", "infrastructure"],
  }),
  build({
    slug: "temporal",
    name: "Temporal",
    githubOrg: "temporalio",
    homepage: "https://temporal.io",
    sector: "developer-tools",
    stage: "series-c",
    what: "Durable workflow orchestration platform. Core Go server, multi-language SDKs (TS/Py/Java/Go/.NET/Ruby/PHP), and visibility primitives all public.",
    momentum: "accelerating",
    repos: "100+ public repos across server, SDKs, and tooling",
    lang: "Go / TypeScript / Python",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "pulumi",
    name: "Pulumi",
    githubOrg: "pulumi",
    homepage: "https://www.pulumi.com",
    sector: "developer-tools",
    stage: "series-c",
    what: "Infrastructure-as-code as actual code — TypeScript, Python, Go, .NET, Java IaC. The cloud-native challenger to Terraform; growing post-HashiCorp acquisition.",
    momentum: "accelerating",
    repos: "200+ public repos across providers and SDKs",
    lang: "Go / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "figma",
    name: "Figma",
    githubOrg: "figma",
    homepage: "https://www.figma.com",
    sector: "productivity",
    stage: "later",
    what: "Collaborative design platform. Public org hosts design-system tooling, the Plugin API, and devtools. Core product is closed but the developer surface is meaningful.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript / Rust",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "plaid",
    name: "Plaid",
    githubOrg: "plaid",
    homepage: "https://plaid.com",
    sector: "fintech",
    stage: "later",
    what: "Banking API platform. Public org hosts SDKs across 10+ languages plus the Link integration kits — the developer surface of US fintech.",
    momentum: "steady",
    repos: "50+ public repos across SDKs and templates",
    lang: "Go / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "twilio",
    name: "Twilio",
    githubOrg: "twilio",
    homepage: "https://www.twilio.com",
    sector: "developer-tools",
    stage: "public",
    what: "Communications API platform. Public org with SDKs across 8+ languages plus Functions, Studio tooling, and the SendGrid+Segment integration surface.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Go / TypeScript / Python",
    related: ["developer-tools", "fintech"],
  }),
  build({
    slug: "netlify",
    name: "Netlify",
    githubOrg: "netlify",
    homepage: "https://www.netlify.com",
    sector: "infrastructure",
    stage: "later",
    what: "Jamstack hosting and edge platform. Public org hosts CLI, build plugins, edge-functions tooling, and the Netlify Identity service.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "sourcegraph",
    name: "Sourcegraph",
    githubOrg: "sourcegraph",
    homepage: "https://sourcegraph.com",
    sector: "developer-tools",
    stage: "later",
    what: "Code intelligence platform with the Cody AI coding assistant. Public org hosts the indexer, language servers, and Cody extensions across major IDEs.",
    momentum: "accelerating",
    repos: "100+ public repos",
    lang: "Go / TypeScript",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "dbt-labs",
    name: "dbt Labs",
    githubOrg: "dbt-labs",
    homepage: "https://www.getdbt.com",
    sector: "analytics",
    stage: "later",
    what: "Analytics engineering tooling. dbt is the de-facto SQL transformation layer for Snowflake, BigQuery, Databricks, and modern Postgres warehouses.",
    momentum: "steady",
    repos: "100+ public repos across adapters and packages",
    lang: "Python / SQL",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "duckdb",
    name: "DuckDB",
    githubOrg: "duckdb",
    homepage: "https://duckdb.org",
    sector: "database",
    stage: "seed",
    what: "In-process analytical database engine. The DuckDB core ships under MIT license with bindings in 10+ languages — the SQLite of analytics.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "C++ / Rust",
    related: ["database", "analytics"],
  }),
  build({
    slug: "honeycomb",
    name: "Honeycomb",
    githubOrg: "honeycombio",
    homepage: "https://www.honeycomb.io",
    sector: "observability",
    stage: "later",
    what: "Observability platform optimized for high-cardinality traces. Public org hosts agents, integrations, OpenTelemetry collectors, and Honeycomb-Lambda layers.",
    momentum: "steady",
    repos: "80+ public repos",
    lang: "Go / TypeScript",
    related: ["observability", "infrastructure"],
  }),
  build({
    slug: "adyen",
    name: "Adyen",
    githubOrg: "Adyen",
    homepage: "https://www.adyen.com",
    sector: "fintech",
    stage: "public",
    what: "European-anchored payments platform. Public org hosts API libraries plus the iDEAL, Klarna, and POS integration tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Java / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  // ───────────────────────── 2026-05-28 expansion 2 (20 orgs) ─────────────────────────
  build({
    slug: "redis",
    name: "Redis",
    githubOrg: "redis",
    homepage: "https://redis.io",
    sector: "database",
    stage: "later",
    what: "In-memory data store and broker. Redis is the de-facto cache layer of modern apps; the public org hosts the core engine plus 12+ client libraries.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "C / Go",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "mariadb",
    name: "MariaDB",
    githubOrg: "MariaDB",
    homepage: "https://mariadb.com",
    sector: "database",
    stage: "public",
    what: "MySQL fork run by the original MySQL team. Open-source relational database with enterprise replication, ColumnStore, and SkySQL cloud tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "C / C++",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "couchbase",
    name: "Couchbase",
    githubOrg: "couchbase",
    homepage: "https://www.couchbase.com",
    sector: "database",
    stage: "public",
    what: "JSON document database with SQL++. Public org hosts the core server, mobile sync, and 10+ SDK languages.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "C++ / Go",
    related: ["database", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "timescale",
    name: "Timescale",
    githubOrg: "timescale",
    homepage: "https://www.timescale.com",
    sector: "database",
    stage: "series-c",
    what: "Postgres extension for time-series data plus a hosted cloud. The TimescaleDB engine ships under Timescale License; SDKs and tooling are MIT.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "C / Go",
    related: ["database", "analytics"],
  }),
  build({
    slug: "meilisearch",
    name: "Meilisearch",
    githubOrg: "meilisearch",
    homepage: "https://www.meilisearch.com",
    sector: "database",
    stage: "series-b",
    what: "Lightweight Rust-native search engine. Open-source core with a hosted cloud — the developer-experience-first alternative to Elasticsearch for app search.",
    momentum: "accelerating",
    repos: "50+ public repos",
    lang: "Rust / TypeScript",
    related: ["database", "developer-tools"],
  }),
  build({
    slug: "typesense",
    name: "Typesense",
    githubOrg: "typesense",
    homepage: "https://typesense.org",
    sector: "database",
    stage: "seed",
    what: "C++ open-source search engine designed as a Meilisearch / Elasticsearch alternative. Hosted Typesense Cloud is the commercial path.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "C++ / TypeScript",
    related: ["database", "developer-tools"],
  }),
  build({
    slug: "weaviate",
    name: "Weaviate",
    githubOrg: "weaviate",
    homepage: "https://weaviate.io",
    sector: "database",
    stage: "series-b",
    what: "Open-source vector database with hybrid search. One of the headline players in the AI-native data layer.",
    momentum: "accelerating",
    repos: "50+ public repos",
    lang: "Go / Python",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "qdrant",
    name: "Qdrant",
    githubOrg: "qdrant",
    homepage: "https://qdrant.tech",
    sector: "database",
    stage: "series-a",
    what: "Rust-native vector database with HNSW indexing. Open-source core plus Qdrant Cloud; widely used in RAG production stacks.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / Python",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "milvus",
    name: "Milvus",
    githubOrg: "milvus-io",
    homepage: "https://milvus.io",
    sector: "database",
    stage: "series-b",
    what: "Open-source distributed vector database from Zilliz. The most-starred open-source vector DB; multi-language SDKs across Python, Go, Java, Node.",
    momentum: "accelerating",
    repos: "40+ public repos",
    lang: "Go / C++",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "bun",
    name: "Bun",
    githubOrg: "oven-sh",
    homepage: "https://bun.sh",
    sector: "developer-tools",
    stage: "series-b",
    what: "All-in-one JavaScript runtime, package manager, bundler, and test runner. Written in Zig with custom JSC integration; one of the most active OSS JS projects.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Zig / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "deno",
    name: "Deno",
    githubOrg: "denoland",
    homepage: "https://deno.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "Secure JavaScript and TypeScript runtime by Ryan Dahl, plus Deno Deploy edge runtime and Deno KV. Rust-based engine with V8.",
    momentum: "accelerating",
    repos: "50+ public repos",
    lang: "Rust / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "amplitude",
    name: "Amplitude",
    githubOrg: "amplitude",
    homepage: "https://amplitude.com",
    sector: "analytics",
    stage: "public",
    what: "Product analytics platform. Public org hosts analytics SDKs across web, iOS, Android, plus the Experiment feature-flag tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Swift / Kotlin",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "mixpanel",
    name: "Mixpanel",
    githubOrg: "mixpanel",
    homepage: "https://mixpanel.com",
    sector: "analytics",
    stage: "later",
    what: "Product analytics platform. Public org hosts SDKs across 12+ platforms plus the JQL exploratory query tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Python / Swift",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "metabase",
    name: "Metabase",
    githubOrg: "metabase",
    homepage: "https://www.metabase.com",
    sector: "analytics",
    stage: "series-c",
    what: "Open-source BI tool. Clojure backend with React frontend; widely adopted at SMB and mid-market for self-serve analytics.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Clojure / TypeScript",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "runway",
    name: "Runway ML",
    githubOrg: "runwayml",
    homepage: "https://runwayml.com",
    sector: "ai-ml",
    stage: "later",
    what: "Generative video and image platform. The category-defining AI video tool with proprietary Gen-* model family; limited public ML surface but active SDK presence.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "creative-tools"],
  }),
  build({
    slug: "stability-ai",
    name: "Stability AI",
    githubOrg: "Stability-AI",
    homepage: "https://stability.ai",
    sector: "ai-ml",
    stage: "series-c",
    what: "Open-weight model lab known for Stable Diffusion. Public org hosts model code, training recipes, and the StableLM language-model family.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python",
    related: ["ai-ml", "creative-tools"],
  }),
  build({
    slug: "ai21-labs",
    name: "AI21 Labs",
    githubOrg: "AI21Labs",
    homepage: "https://www.ai21.com",
    sector: "ai-ml",
    stage: "series-c",
    what: "Israeli frontier-AI lab. Builds the Jamba and Jurassic model families with strong reasoning and long-context focus. SDK + API tooling public.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml"],
  }),
  build({
    slug: "pinecone",
    name: "Pinecone",
    githubOrg: "pinecone-io",
    homepage: "https://www.pinecone.io",
    sector: "database",
    stage: "series-b",
    what: "Managed vector database optimized for retrieval-augmented generation. Proprietary engine with public SDKs and integration tooling.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python / TypeScript",
    related: ["database", "ai-ml"],
  }),
  build({
    slug: "writer",
    name: "Writer",
    githubOrg: "writer",
    homepage: "https://writer.com",
    sector: "ai-ml",
    stage: "series-c",
    what: "Enterprise generative AI platform with the Palmyra model family. Focus on regulated industries with on-prem deployment options.",
    momentum: "steady",
    repos: "15+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-ml", "productivity"],
  }),
  build({
    slug: "weights-biases",
    name: "Weights & Biases",
    githubOrg: "wandb",
    homepage: "https://wandb.ai",
    sector: "developer-tools",
    stage: "series-c",
    what: "ML experiment tracking, model registry, and evaluation platform. Public org hosts the wandb SDK, Weave LLM observability layer, and Launch.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Python / TypeScript",
    related: ["developer-tools", "ai-ml", "observability"],
  }),
  // ───────────────────────── 2026-05-28 expansion 3 (15 orgs — cross 1000) ─────────────────────────
  build({
    slug: "cockroachdb",
    name: "CockroachDB",
    githubOrg: "cockroachdb",
    homepage: "https://www.cockroachlabs.com",
    sector: "database",
    stage: "later",
    what: "Distributed SQL database from Cockroach Labs. Strong PostgreSQL compatibility, global low-latency replication, serverless tier. Founded by ex-Google Spanner engineers.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Go",
    related: ["database", "infrastructure"],
  }),
  build({
    slug: "influxdata",
    name: "InfluxData",
    githubOrg: "influxdata",
    homepage: "https://www.influxdata.com",
    sector: "database",
    stage: "later",
    what: "Time-series database platform with InfluxDB OSS, Cloud, and Enterprise tiers. Major IoT and observability data layer; recently shifted core engine to Rust.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Go / Rust",
    related: ["database", "observability", "infrastructure"],
  }),
  build({
    slug: "dremio",
    name: "Dremio",
    githubOrg: "dremio",
    homepage: "https://www.dremio.com",
    sector: "database",
    stage: "later",
    what: "Open lakehouse platform built on Apache Iceberg and Apache Arrow. Query engine on top of cloud data lakes with strong SQL semantics.",
    momentum: "steady",
    repos: "80+ public repos",
    lang: "Java / TypeScript",
    related: ["database", "analytics"],
  }),
  build({
    slug: "astro",
    name: "Astro",
    githubOrg: "withastro",
    homepage: "https://astro.build",
    sector: "developer-tools",
    stage: "series-a",
    what: "Multi-framework static site generator with islands architecture. Strong content-site focus competing with Next.js for content-heavy use cases.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["developer-tools"],
  }),
  build({
    slug: "nuxt",
    name: "Nuxt (NuxtLabs)",
    githubOrg: "nuxt",
    homepage: "https://nuxt.com",
    sector: "developer-tools",
    stage: "seed",
    what: "Vue.js meta-framework plus commercial team (NuxtLabs). Stripe-style developer surface for the Vue ecosystem with strong SSR and edge-runtime story.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "TypeScript",
    related: ["developer-tools"],
  }),
  build({
    slug: "tauri",
    name: "Tauri (CrabNebula)",
    githubOrg: "tauri-apps",
    homepage: "https://tauri.app",
    sector: "developer-tools",
    stage: "seed",
    what: "Rust-based desktop app framework competing with Electron. Smaller binary, better performance, native OS bindings. CrabNebula is the commercial team.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "ory",
    name: "Ory",
    githubOrg: "ory",
    homepage: "https://www.ory.sh",
    sector: "developer-tools",
    stage: "series-a",
    what: "Open-source identity infrastructure — Kratos (identity), Hydra (OAuth2), Keto (authorization), Oathkeeper (zero trust). Self-hostable Auth0 alternative.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Go / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "kong",
    name: "Kong",
    githubOrg: "Kong",
    homepage: "https://konghq.com",
    sector: "infrastructure",
    stage: "later",
    what: "API gateway and microservices management platform. Kong Gateway is OSS (Lua + nginx); Kong Konnect is the commercial cloud. Strong AI Gateway momentum in 2025-2026.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Lua / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "langfuse",
    name: "Langfuse",
    githubOrg: "langfuse",
    homepage: "https://langfuse.com",
    sector: "observability",
    stage: "seed",
    what: "LLM observability and evaluation platform. Open-source core plus cloud. Strong RAG and agent-trace use cases; rapid adoption in 2025-2026 agent-infra stacks.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript / Python",
    related: ["observability", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "arize-ai",
    name: "Arize AI",
    githubOrg: "Arize-ai",
    homepage: "https://arize.com",
    sector: "observability",
    stage: "series-b",
    what: "ML observability platform with strong LLM evaluation focus. Phoenix is their open-source LLM tracing tool; commercial cloud handles enterprise-scale eval workflows.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["observability", "ai-ml"],
  }),
  build({
    slug: "braintrust",
    name: "Braintrust",
    githubOrg: "braintrustdata",
    homepage: "https://www.braintrust.dev",
    sector: "observability",
    stage: "series-a",
    what: "LLM eval and observability platform with 'evals as code' philosophy. Competes with Helicone, Langfuse, and Arize on the LLM-app observability frontier.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript",
    related: ["observability", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "helicone",
    name: "Helicone",
    githubOrg: "Helicone",
    homepage: "https://www.helicone.ai",
    sector: "observability",
    stage: "seed",
    what: "LLM observability proxy plus dashboard. Drop-in OpenAI-API-compatible proxy that logs every request; YC-backed with strong indie-developer adoption.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript",
    related: ["observability", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "voyage-ai",
    name: "Voyage AI",
    githubOrg: "voyage-ai",
    homepage: "https://www.voyageai.com",
    sector: "ai-ml",
    stage: "seed",
    what: "Embedding-model specialist focused on retrieval-augmented generation accuracy. Acquired by MongoDB in early 2025 as their RAG/embedding stack.",
    momentum: "steady",
    repos: "10+ public repos",
    lang: "Python",
    related: ["ai-ml", "database"],
  }),
  build({
    slug: "jina-ai",
    name: "Jina AI",
    githubOrg: "jina-ai",
    homepage: "https://jina.ai",
    sector: "ai-ml",
    stage: "series-a",
    what: "Open-source neural search and embedding infrastructure. Builds Jina (multi-modal AI framework), CLIP embeddings, and reranker models for the search stack.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python",
    related: ["ai-ml", "database", "developer-tools"],
  }),
  build({
    slug: "backstage",
    name: "Backstage (Spotify)",
    githubOrg: "backstage",
    homepage: "https://backstage.io",
    sector: "developer-tools",
    stage: "later",
    what: "Developer portal platform for managing services, docs, and tooling. Open-sourced by Spotify in 2020; now a CNCF incubating project with broad enterprise adoption.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "infrastructure", "productivity"],
  }),
  // ───────────────────────── 2026-05-29 expansion 4 (15 orgs — fintech/analytics/prod gaps) ─────────────────────────
  build({
    slug: "wise",
    name: "Wise",
    githubOrg: "transferwise",
    homepage: "https://wise.com",
    sector: "fintech",
    stage: "public",
    what: "Cross-border payments platform (formerly TransferWise). Strong public engineering footprint with comprehensive SDK and integration tooling across multiple languages.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Java / Kotlin",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "nubank",
    name: "Nubank",
    githubOrg: "nubank",
    homepage: "https://nubank.com.br",
    sector: "fintech",
    stage: "public",
    what: "Brazilian neobank and the largest digital bank in Latin America. Public engineering presence anchored around Clojure tooling and microservices infrastructure.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Clojure / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "monzo",
    name: "Monzo",
    githubOrg: "monzo",
    homepage: "https://monzo.com",
    sector: "fintech",
    stage: "later",
    what: "UK neobank known for engineering blog culture and microservices-heavy architecture. Public org hosts open-source tooling around Cassandra, gRPC, and Kubernetes operations.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "Go / Python",
    related: ["fintech", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "n26",
    name: "N26",
    githubOrg: "n26",
    homepage: "https://n26.com",
    sector: "fintech",
    stage: "later",
    what: "German digital bank serving multiple European markets. Public org hosts SDK tooling and architectural primitives around their pan-European banking infrastructure.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Kotlin / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "fivetran",
    name: "Fivetran",
    githubOrg: "fivetran",
    homepage: "https://www.fivetran.com",
    sector: "analytics",
    stage: "later",
    what: "Automated ELT data pipeline platform connecting hundreds of SaaS sources to data warehouses. Public org hosts connector SDKs, dbt integration, and customer-extension tooling.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "Java / TypeScript",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "airbyte",
    name: "Airbyte",
    githubOrg: "airbytehq",
    homepage: "https://airbyte.com",
    sector: "analytics",
    stage: "series-b",
    what: "Open-source data integration platform with 350+ connectors. The OSS challenger to Fivetran with strong community-built connector momentum.",
    // Downgraded 2026-05-30: current-period (q2-2026) public commit velocity -89%.
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Python / Java",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "cube",
    name: "Cube",
    githubOrg: "cube-js",
    homepage: "https://cube.dev",
    sector: "analytics",
    stage: "series-b",
    what: "Semantic layer and headless BI platform. Open-source core (Cube.js) plus Cube Cloud. Strong adoption for embedded analytics and AI-grounded BI use cases in 2025-2026.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Rust / TypeScript",
    related: ["analytics", "developer-tools", "database"],
  }),
  build({
    slug: "preset",
    name: "Preset",
    githubOrg: "preset-io",
    homepage: "https://preset.io",
    sector: "analytics",
    stage: "series-b",
    what: "Managed Apache Superset platform. Commercial vendor for the open-source Superset BI tool, founded by the original Superset creator (Maxime Beauchemin).",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python / TypeScript",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "hex",
    name: "Hex",
    githubOrg: "hex-inc",
    homepage: "https://hex.tech",
    sector: "analytics",
    stage: "series-c",
    what: "Collaborative data workspace combining notebooks, SQL, and BI dashboards. Strong adoption with modern data teams; AI-grounded analytics is a 2025-2026 product focus.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript / Python",
    related: ["analytics", "developer-tools", "productivity"],
  }),
  build({
    slug: "retool",
    name: "Retool",
    githubOrg: "tryretool",
    homepage: "https://retool.com",
    sector: "productivity",
    stage: "series-c",
    what: "Internal tools platform — drag-and-drop interface builder backed by SQL, REST, and GraphQL. Strong adoption with engineering and ops teams for replacing custom internal dashboards.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "coda",
    name: "Coda",
    githubOrg: "coda-io",
    homepage: "https://coda.io",
    sector: "productivity",
    stage: "later",
    what: "Document-and-database hybrid productivity platform competing with Notion. Public org hosts the Coda Packs SDK for third-party integrations.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "miro",
    name: "Miro",
    githubOrg: "miroapp",
    homepage: "https://miro.com",
    sector: "productivity",
    stage: "later",
    what: "Collaborative whiteboard platform widely adopted for design workshops, sprint planning, and remote-team workflows. Public org hosts Web SDK and app marketplace tooling.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "monday",
    name: "Monday.com",
    githubOrg: "monday-com",
    homepage: "https://monday.com",
    sector: "productivity",
    stage: "public",
    what: "Work management platform with strong customization and integration depth. Public org hosts apps SDK, GraphQL tooling, and integration primitives for the Monday Apps Marketplace.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "TypeScript / Ruby",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "asana",
    name: "Asana",
    githubOrg: "Asana",
    homepage: "https://asana.com",
    sector: "productivity",
    stage: "public",
    what: "Work management platform with strong API ecosystem. Public org hosts SDK clients across major languages plus the Luna React framework that powers their web app.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Python",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "zapier",
    name: "Zapier",
    githubOrg: "zapier",
    homepage: "https://zapier.com",
    sector: "productivity",
    stage: "later",
    what: "No-code automation platform connecting 7,000+ apps. Public org hosts the Zapier Platform CLI, app templates, and connector developer tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "TypeScript / Python",
    related: ["productivity", "developer-tools"],
  }),
  // ───────────────────────── 2026-05-29 expansion 5 (15 orgs — AI-infra + ML platforms) ─────────────────────────
  build({
    slug: "anyscale",
    name: "Anyscale",
    githubOrg: "anyscale",
    homepage: "https://www.anyscale.com",
    sector: "ai-infra",
    stage: "later",
    what: "Commercial vendor for Ray, the distributed compute framework. Founded by Ray creators at UC Berkeley RISELab. Cloud platform for distributed ML training and serving.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Python / Rust",
    related: ["ai-infra", "ai-ml", "infrastructure"],
  }),
  build({
    slug: "vllm",
    name: "vLLM",
    githubOrg: "vllm-project",
    homepage: "https://www.vllm.ai",
    sector: "ai-infra",
    stage: "seed",
    what: "High-throughput LLM serving engine originated at UC Berkeley Sky Computing Lab. The de-facto open-source LLM inference engine in 2025-2026; commercial backing via Neural Magic (acquired by Red Hat/IBM).",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Python / CUDA",
    related: ["ai-infra", "ai-ml"],
  }),
  build({
    slug: "llamaindex",
    name: "LlamaIndex",
    githubOrg: "run-llama",
    homepage: "https://www.llamaindex.ai",
    sector: "developer-tools",
    stage: "series-a",
    what: "RAG and LLM application framework with strong focus on data ingestion, indexing, and retrieval. The Python ecosystem's leading RAG framework alongside LangChain.",
    momentum: "accelerating",
    repos: "30+ public repos",
    lang: "Python / TypeScript",
    related: ["developer-tools", "ai-ml", "database"],
  }),
  build({
    slug: "haystack",
    name: "Haystack (deepset)",
    githubOrg: "deepset-ai",
    homepage: "https://haystack.deepset.ai",
    sector: "developer-tools",
    stage: "series-b",
    what: "Open-source LLM application framework focused on production-grade RAG, semantic search, and agentic workflows. Commercial vendor deepset offers managed deployment and enterprise features.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "modular",
    name: "Modular",
    githubOrg: "modularml",
    homepage: "https://www.modular.com",
    sector: "developer-tools",
    stage: "series-c",
    what: "Builds Mojo programming language (Python superset with C++-level performance) and MAX, an AI deployment platform. Founded by Chris Lattner (LLVM, Swift, TPU creator).",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Mojo / Rust",
    related: ["developer-tools", "ai-infra", "ai-ml"],
  }),
  build({
    slug: "codeium",
    name: "Codeium / Windsurf",
    githubOrg: "Exafunction",
    homepage: "https://codeium.com",
    sector: "developer-tools",
    stage: "series-c",
    what: "AI coding assistant + Windsurf IDE. Closed-source extension with broad IDE coverage; competes directly with Cursor and Claude Code on the AI-coding frontier.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "TypeScript / Rust",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "continue",
    name: "Continue",
    githubOrg: "continuedev",
    homepage: "https://continue.dev",
    sector: "developer-tools",
    stage: "seed",
    what: "Open-source AI coding assistant with native VS Code and JetBrains integration. Customizable model and provider selection; competitor to Cursor with stronger OSS positioning.",
    momentum: "accelerating",
    repos: "10+ public repos",
    lang: "TypeScript",
    related: ["developer-tools", "ai-ml"],
  }),
  build({
    slug: "lambda-labs",
    name: "Lambda Labs",
    githubOrg: "lambdalabs",
    homepage: "https://lambdalabs.com",
    sector: "ai-infra",
    stage: "later",
    what: "GPU cloud platform for AI training and inference. Public org hosts the Lambda Stack (Linux ML environment) and managed GPU workstation tooling.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python",
    related: ["ai-infra", "infrastructure"],
  }),
  build({
    slug: "runpod",
    name: "RunPod",
    githubOrg: "runpod",
    homepage: "https://www.runpod.io",
    sector: "ai-infra",
    stage: "series-a",
    what: "GPU cloud platform with serverless and dedicated GPU options. Strong indie-developer adoption for fine-tuning, training, and inference workloads.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["ai-infra", "infrastructure"],
  }),
  build({
    slug: "coreweave",
    name: "CoreWeave",
    githubOrg: "coreweave-org",
    homepage: "https://www.coreweave.com",
    sector: "ai-infra",
    stage: "public",
    what: "Specialized GPU cloud platform that IPO'd in 2025 as one of the largest AI-infra public-market debuts. Major OpenAI and Mistral capacity supplier.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "Go / Python",
    related: ["ai-infra", "infrastructure"],
  }),
  build({
    slug: "comet-ml",
    name: "Comet",
    githubOrg: "comet-ml",
    homepage: "https://www.comet.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "ML experiment tracking, model registry, and observability platform. Competes with Weights & Biases on ML-experiment infrastructure with strong enterprise traction.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["developer-tools", "ai-ml", "observability"],
  }),
  build({
    slug: "bentoml",
    name: "BentoML",
    githubOrg: "bentoml",
    homepage: "https://www.bentoml.com",
    sector: "ai-infra",
    stage: "series-a",
    what: "Open-source platform for packaging and deploying ML models as production-grade services. Strong adoption for serving custom and fine-tuned models in regulated environments.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python",
    related: ["ai-infra", "developer-tools", "ai-ml"],
  }),
  build({
    slug: "outerbounds",
    name: "Outerbounds",
    githubOrg: "outerbounds",
    homepage: "https://outerbounds.com",
    sector: "developer-tools",
    stage: "series-a",
    what: "Commercial vendor for Metaflow, Netflix's open-source ML workflow framework. Cloud platform for ML and AI infrastructure spanning experimentation to production.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python",
    related: ["developer-tools", "ai-ml", "ai-infra"],
  }),
  build({
    slug: "ollama",
    name: "Ollama",
    githubOrg: "ollama",
    homepage: "https://ollama.com",
    sector: "developer-tools",
    stage: "seed",
    what: "Easy local LLM runtime for running open-weight models on consumer hardware. The de-facto path for indie-developer and prosumer local-inference workflows.",
    momentum: "accelerating",
    repos: "15+ public repos",
    lang: "Go / Python",
    related: ["developer-tools", "ai-ml", "ai-infra"],
  }),
  build({
    slug: "predibase",
    name: "Predibase",
    githubOrg: "predibase",
    homepage: "https://predibase.com",
    sector: "ai-ml",
    stage: "series-b",
    what: "Commercial vendor for Ludwig, an open-source low-code ML framework. Platform for fine-tuning and serving open-weight LLMs with strong enterprise adoption.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python",
    related: ["ai-ml", "developer-tools", "ai-infra"],
  }),
  // ───────────────────────── 2026-05-29 expansion 6 (15 orgs — infra + obs + DevOps) ─────────────────────────
  build({
    slug: "digitalocean",
    name: "DigitalOcean",
    githubOrg: "digitalocean",
    homepage: "https://www.digitalocean.com",
    sector: "infrastructure",
    stage: "public",
    what: "Developer-focused cloud platform with predictable pricing. Public org hosts the doctl CLI, Kubernetes tooling, App Platform integrations, and Marketplace 1-click images.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Go / TypeScript",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "scaleway",
    name: "Scaleway",
    githubOrg: "scaleway",
    homepage: "https://www.scaleway.com",
    sector: "infrastructure",
    stage: "later",
    what: "European cloud provider (Iliad Group subsidiary) with strong sovereign-cloud positioning. Public org hosts CLIs, Terraform providers, and Kubernetes operators.",
    momentum: "steady",
    repos: "80+ public repos",
    lang: "Go / TypeScript",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "render",
    name: "Render",
    githubOrg: "renderinc",
    homepage: "https://render.com",
    sector: "infrastructure",
    stage: "series-b",
    what: "Unified cloud platform competing with Heroku and Vercel for full-stack app deployment. Strong developer-experience focus with native git-driven deploys, managed Postgres, and Redis.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "traefik-labs",
    name: "Traefik Labs",
    githubOrg: "traefik",
    homepage: "https://traefik.io",
    sector: "infrastructure",
    stage: "series-b",
    what: "Commercial vendor for Traefik, the cloud-native edge router and load balancer. Strong adoption in Kubernetes environments; Traefik Hub adds API management on top of the open-source core.",
    momentum: "steady",
    repos: "40+ public repos",
    lang: "Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "buoyant",
    name: "Buoyant (Linkerd)",
    githubOrg: "linkerd",
    homepage: "https://buoyant.io",
    sector: "infrastructure",
    stage: "series-a",
    what: "Commercial vendor for Linkerd, the original CNCF service mesh. Smaller and simpler than Istio with strong Rust-based data plane; Buoyant Enterprise handles production support.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Rust / Go",
    related: ["infrastructure", "observability"],
  }),
  build({
    slug: "rancher",
    name: "Rancher (SUSE)",
    githubOrg: "rancher",
    homepage: "https://www.rancher.com",
    sector: "infrastructure",
    stage: "public",
    what: "Kubernetes management platform now under SUSE. Public org hosts Rancher core, K3s (lightweight Kubernetes), Longhorn (cloud-native storage), and Fleet (GitOps).",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Go",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "portainer",
    name: "Portainer",
    githubOrg: "portainer",
    homepage: "https://www.portainer.io",
    sector: "infrastructure",
    stage: "series-a",
    what: "Container management platform with strong UI focus across Docker, Kubernetes, and Nomad. Popular for self-hosted homelab and SMB Kubernetes deployments.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Go / TypeScript",
    related: ["infrastructure", "developer-tools"],
  }),
  build({
    slug: "koyeb",
    name: "Koyeb",
    githubOrg: "koyeb",
    homepage: "https://www.koyeb.com",
    sector: "infrastructure",
    stage: "series-a",
    what: "Serverless deployment platform with native GPU support for AI workloads. Strong European developer-experience focus competing with Render and Fly.io.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Go / TypeScript",
    related: ["infrastructure", "ai-infra", "developer-tools"],
  }),
  build({
    slug: "signoz",
    name: "SigNoz",
    githubOrg: "SigNoz",
    homepage: "https://signoz.io",
    sector: "observability",
    stage: "series-a",
    what: "Open-source observability platform built on OpenTelemetry. Strong adoption as the OSS challenger to Datadog and New Relic; ClickHouse-backed for high-cardinality data.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "Go / TypeScript",
    related: ["observability", "infrastructure"],
  }),
  build({
    slug: "axiom",
    name: "Axiom",
    githubOrg: "axiomhq",
    homepage: "https://axiom.co",
    sector: "observability",
    stage: "series-a",
    what: "Modern observability platform with strong logs and event-data focus. Distinctive economics on high-volume data with serverless storage backend.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Go / TypeScript",
    related: ["observability", "developer-tools"],
  }),
  build({
    slug: "betterstack",
    name: "Better Stack",
    githubOrg: "BetterStackHQ",
    homepage: "https://betterstack.com",
    sector: "observability",
    stage: "series-a",
    what: "Modern monitoring and incident management platform combining uptime monitoring, logs, and on-call paging. Strong product-led growth across SMB developer teams.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Ruby / TypeScript",
    related: ["observability", "developer-tools"],
  }),
  build({
    slug: "pagerduty",
    name: "PagerDuty",
    githubOrg: "PagerDuty",
    homepage: "https://www.pagerduty.com",
    sector: "observability",
    stage: "public",
    what: "Incident response and digital operations management platform. Public org hosts SDKs across major languages plus integration tooling for the PagerDuty Marketplace.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Ruby / TypeScript",
    related: ["observability", "developer-tools"],
  }),
  build({
    slug: "gitlab",
    name: "GitLab",
    githubOrg: "gitlabhq",
    homepage: "https://gitlab.com",
    sector: "developer-tools",
    stage: "public",
    what: "End-to-end DevOps platform spanning Git hosting, CI/CD, container registry, and security scanning. Public engineering mirrors on GitHub with the canonical repo on gitlab.com.",
    momentum: "steady",
    repos: "20+ public repos (mirror); 100+ on gitlab.com",
    lang: "Ruby / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "circleci",
    name: "CircleCI",
    githubOrg: "CircleCI-Public",
    homepage: "https://circleci.com",
    sector: "developer-tools",
    stage: "later",
    what: "CI/CD platform with strong cloud-native deployment story. Public org hosts orbs (reusable config packages), runner installers, and CLI tooling.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Clojure / TypeScript",
    related: ["developer-tools", "infrastructure"],
  }),
  build({
    slug: "buildkite",
    name: "Buildkite",
    githubOrg: "buildkite",
    homepage: "https://buildkite.com",
    sector: "developer-tools",
    stage: "series-b",
    what: "CI/CD platform optimized for hybrid cloud — control plane in Buildkite, agents on customer infrastructure. Strong adoption with engineering orgs running large-scale build farms.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Go / Ruby",
    related: ["developer-tools", "infrastructure"],
  }),
  // ───────────────────────── 2026-05-29 expansion 7 (15 orgs — fintech crypto + obs legacy + prod + analytics) ─────────────────────────
  build({
    slug: "coinbase",
    name: "Coinbase",
    githubOrg: "coinbase",
    homepage: "https://www.coinbase.com",
    sector: "fintech",
    stage: "public",
    what: "Largest US crypto exchange. Public engineering org hosts the Base L2 chain, Coinbase Cloud node infrastructure, and broad blockchain developer tooling.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "TypeScript / Go / Rust",
    related: ["fintech", "developer-tools", "infrastructure"],
  }),
  build({
    slug: "circle",
    name: "Circle (USDC)",
    githubOrg: "circlefin",
    homepage: "https://www.circle.com",
    sector: "fintech",
    stage: "public",
    what: "Issuer of USDC stablecoin and broader Web3 financial infrastructure. Public org hosts smart contract verifiers, wallet SDKs, and the Circle Web3 Services tooling.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "Solidity / TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "alchemy",
    name: "Alchemy",
    githubOrg: "alchemyplatform",
    homepage: "https://www.alchemy.com",
    sector: "fintech",
    stage: "later",
    what: "Web3 development platform with node infrastructure, Account Abstraction stack, and developer tooling across Ethereum, Solana, Polygon, Base, and Optimism.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "TypeScript / Rust",
    related: ["fintech", "developer-tools", "infrastructure"],
  }),
  build({
    slug: "privy",
    name: "Privy",
    githubOrg: "privy-io",
    homepage: "https://www.privy.io",
    sector: "fintech",
    stage: "series-b",
    what: "Embedded wallet and authentication platform for Web3 apps. Strong adoption with consumer crypto apps; SDK-first integration model.",
    momentum: "accelerating",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["fintech", "developer-tools"],
  }),
  build({
    slug: "gusto",
    name: "Gusto",
    githubOrg: "gusto",
    homepage: "https://gusto.com",
    sector: "fintech",
    stage: "later",
    what: "SMB payroll, benefits, and HR platform. Public org hosts the Gusto Embedded SDK, partner-integration tooling, and OAuth provider tooling.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "Ruby / TypeScript",
    related: ["fintech", "productivity", "developer-tools"],
  }),
  build({
    slug: "newrelic",
    name: "New Relic",
    githubOrg: "newrelic",
    homepage: "https://newrelic.com",
    sector: "observability",
    stage: "public",
    what: "Application performance monitoring and observability platform. Public org hosts agents across major languages, OpenTelemetry distributions, and the Pixie eBPF-based observability layer.",
    momentum: "steady",
    repos: "300+ public repos",
    lang: "Go / Java",
    related: ["observability", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "dynatrace",
    name: "Dynatrace",
    githubOrg: "Dynatrace",
    homepage: "https://www.dynatrace.com",
    sector: "observability",
    stage: "public",
    what: "Enterprise observability and AIOps platform with strong APM, infrastructure, and security monitoring. Public org hosts OneAgent integrations and OpenTelemetry tooling.",
    momentum: "steady",
    repos: "100+ public repos",
    lang: "Java / Go",
    related: ["observability", "infrastructure"],
  }),
  build({
    slug: "splunk",
    name: "Splunk",
    githubOrg: "splunk",
    homepage: "https://www.splunk.com",
    sector: "observability",
    stage: "public",
    what: "SIEM and log management platform now under Cisco (2024 $28B acquisition). Public org hosts the Splunk Connect tooling, observability cloud agents, and Splunk Cloud integrations.",
    momentum: "steady",
    repos: "200+ public repos",
    lang: "Python / TypeScript",
    related: ["observability", "infrastructure"],
  }),
  build({
    slug: "sumologic",
    name: "Sumo Logic",
    githubOrg: "SumoLogic",
    homepage: "https://www.sumologic.com",
    sector: "observability",
    stage: "later",
    what: "Cloud-native log management and SIEM platform. Public org hosts SDK clients and collector tooling for hybrid-cloud log aggregation.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "Scala / Go",
    related: ["observability", "infrastructure"],
  }),
  build({
    slug: "canva",
    name: "Canva",
    githubOrg: "canvanauts",
    homepage: "https://www.canva.com",
    sector: "productivity",
    stage: "later",
    what: "Visual content creation platform with strong template ecosystem. Public org hosts Canva Apps SDK, Connect API integrations, and partner extension tooling.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "thoughtspot",
    name: "ThoughtSpot",
    githubOrg: "thoughtspot",
    homepage: "https://www.thoughtspot.com",
    sector: "analytics",
    stage: "later",
    what: "AI-native search-based analytics platform. Strong embedded analytics story; Sage AI engine adds natural-language data exploration on top of the SpotIQ engine.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "TypeScript / Python",
    related: ["analytics", "ai-ml", "developer-tools"],
  }),
  build({
    slug: "clickup",
    name: "ClickUp",
    githubOrg: "clickup",
    homepage: "https://clickup.com",
    sector: "productivity",
    stage: "series-c",
    what: "All-in-one productivity platform combining tasks, docs, goals, and chat. Aggressive feature breadth competing with Notion, Asana, and Monday.com.",
    momentum: "steady",
    repos: "15+ public repos",
    lang: "TypeScript",
    related: ["productivity", "developer-tools"],
  }),
  build({
    slug: "mode",
    name: "Mode (ThoughtSpot)",
    githubOrg: "mode",
    homepage: "https://mode.com",
    sector: "analytics",
    stage: "later",
    what: "Collaborative analytics platform combining SQL, Python, R, and BI dashboards. Acquired by ThoughtSpot in 2023; serves analytical teams at mid-market and enterprise companies.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "Python / TypeScript",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "heap",
    name: "Heap (Contentsquare)",
    githubOrg: "heap",
    homepage: "https://heap.io",
    sector: "analytics",
    stage: "later",
    what: "Autocapture product analytics platform. Acquired by Contentsquare in 2024; serves product teams who want event tracking without manual instrumentation.",
    momentum: "steady",
    repos: "20+ public repos",
    lang: "TypeScript / Python",
    related: ["analytics", "developer-tools"],
  }),
  build({
    slug: "sigma-computing",
    name: "Sigma Computing",
    githubOrg: "sigmacomputing",
    homepage: "https://www.sigmacomputing.com",
    sector: "analytics",
    stage: "later",
    what: "Spreadsheet-style BI tool for cloud data warehouses (Snowflake, BigQuery, Databricks). Strong adoption with operations teams comfortable with spreadsheet semantics.",
    momentum: "steady",
    repos: "15+ public repos",
    lang: "TypeScript",
    related: ["analytics", "developer-tools"],
  }),

  // --- Gaming / game infrastructure ---
  // Curated game-infrastructure companies (backends, multiplayer, orchestration,
  // avatars) with self-published public GitHub orgs. Studios are deliberately
  // excluded — the fundable, signal-legible shape in gaming is infrastructure.
  build({
    slug: "heroic-labs",
    name: "Heroic Labs",
    githubOrg: "heroiclabs",
    homepage: "https://heroiclabs.com",
    sector: "gaming",
    stage: "seed",
    what: "Maker of Nakama, the leading open-source game backend — multiplayer, matchmaking, leaderboards, chat, and social services used by studios and publishers. A textbook game-infrastructure shape where the product is the public GitHub org.",
    momentum: "steady",
    repos: "35+ public repos",
    lang: "Go / C#",
    related: ["gaming", "infrastructure", "developer-tools"],
  }),
  build({
    slug: "hathora",
    name: "Hathora",
    githubOrg: "hathora",
    homepage: "https://hathora.dev",
    sector: "gaming",
    stage: "seed",
    what: "Serverless hosting and orchestration for multiplayer game servers — deploy and scale game servers worldwide with no ops. Raised a $7.6M seed (Upfront Ventures, Founders Fund) in 2023.",
    momentum: "steady",
    repos: "50+ public repos",
    lang: "TypeScript / C#",
    related: ["gaming", "infrastructure"],
  }),
  build({
    slug: "edgegap",
    name: "Edgegap",
    githubOrg: "edgegap",
    homepage: "https://edgegap.com",
    sector: "gaming",
    stage: "series-a",
    what: "Edge game-server orchestration that auto-deploys multiplayer servers close to players to cut latency, no ops required. Raised a $7M Series A led by Konvoy Ventures.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "C# / Go",
    related: ["gaming", "infrastructure"],
  }),
  build({
    slug: "beamable",
    name: "Beamable",
    githubOrg: "beamable",
    homepage: "https://beamable.com",
    sector: "gaming",
    stage: "series-a",
    what: "Unity-native live-game backend for identity, economy, social, and live-ops, now building open decentralized (DePIN) backend infrastructure for games. Raised a $13.5M Series A led by BITKRAFT in 2025.",
    momentum: "steady",
    repos: "60+ public repos",
    lang: "C# / ShaderLab",
    related: ["gaming", "infrastructure"],
  }),
  build({
    slug: "ready-player-me",
    name: "Ready Player Me",
    githubOrg: "readyplayerme",
    homepage: "https://readyplayer.me",
    sector: "gaming",
    stage: "series-b",
    what: "Cross-game avatar platform — one 3D avatar players carry across thousands of games and apps. Raised a $56M Series B led by a16z in 2022.",
    momentum: "steady",
    repos: "30+ public repos",
    lang: "C++ / C#",
    related: ["gaming"],
  }),
  build({
    slug: "pragma",
    name: "Pragma",
    githubOrg: "pragmaplatform",
    homepage: "https://pragma.gg",
    sector: "gaming",
    stage: "series-b",
    what: "Backend platform for live-service games — accounts, social, store, matchmaking, and game data as one integrated system, trusted by studios including Bungie and Remedy. Raised a $22M Series B led by Insight Partners.",
    momentum: "steady",
    repos: "15+ public repos",
    lang: "Rust",
    related: ["gaming", "infrastructure"],
  }),
];

export function getCompany(slug: string): Company | undefined {
  return companies.find((c) => c.slug === slug);
}

export function getAllCompanySlugs(): string[] {
  return companies.map((c) => c.slug);
}
