/**
 * Shared badge dimension math.
 *
 * The badge SVGs generated by app/api/badge/* size themselves from the
 * label and value text lengths (label.length * 8 + 24 per side, 28px tall).
 * Pages that RENDER those badges can compute the exact intrinsic size with
 * the same formula and emit width/height attributes, so the browser
 * reserves the correct box before the SVG arrives (CLS contribution 0).
 * Keep this in sync with badgeSvg() in app/api/badge/[name]/route.tsx.
 */

export const BADGE_HEIGHT = 28;

export const BADGE_LABEL = "engineering momentum";

/** Intrinsic SVG width for a [name]-style momentum badge. */
export function badgeWidth(label: string, value: string): number {
  return label.length * 8 + 24 + value.length * 8 + 24;
}

/** Value string exactly as app/api/badge/[name]/route.tsx builds it. */
export function badgeValue(velocity: number, signalType: string): string {
  const word = (signalType || "steady").replace(/ .+/, "");
  return `${word} ${velocity} commits`;
}
