/**
 * Auto-generated by tools/audio/generate.mjs. Do not edit by hand.
 * Run `node tools/audio/generate.mjs` to regenerate.
 *
 * This placeholder ships with no clips so DataNerdAudio renders as null
 * until audio is generated against the Cartesia voice.
 */
export type DataNerdClip = {
  durationSec: number;
  bytes: number;
  chars: number;
  generatedAt?: string;
};

export type DataNerdManifest = {
  voice: { name: string; model: string };
  generatedAt: string;
  clips: Record<string, DataNerdClip>;
};

export const dataNerdManifest: DataNerdManifest = {
  voice: { name: "The Data Nerd", model: "sonic-2" },
  generatedAt: "1970-01-01T00:00:00.000Z",
  clips: {},
};
