import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Founder Profile Opt-Out",
  description:
    "Request removal of a /founder/[handle] page. Verified removal requests are honored within 7 business days; the page then returns HTTP 410 Gone and the handle is added to a permanent blocklist.",
  alternates: { canonical: "/founder/opt-out" },
  robots: { index: true, follow: false },
};

export const revalidate = 604800;

export default function OptOutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <nav className="mb-6 text-sm text-gray-400" aria-label="Breadcrumb">
        <Link href="/" className="hover:text-gray-300 transition-colors">
          All Sectors
        </Link>
        <span className="mx-2">/</span>
        <Link href="/founder" className="hover:text-gray-300 transition-colors">
          Founders
        </Link>
        <span className="mx-2">/</span>
        <span className="text-gray-400">Opt-Out</span>
      </nav>

      <h1 className="text-3xl sm:text-4xl font-bold text-gray-100 mb-4 leading-tight">
        Founder Profile Opt-Out
      </h1>
      <p className="text-sky-400 text-base leading-relaxed mb-6 font-medium">
        Request removal of a /founder/[handle] page from VC Deal Flow Signal.
      </p>

      <section className="mb-10" aria-label="Eligibility">
        <h2 className="text-xl font-semibold text-gray-100 mb-3">Who can request removal</h2>
        <p className="text-gray-400 text-sm leading-relaxed">
          Anyone profiled on a /founder/[handle] page. Requests must come from the verified email associated with the public-figure identity, typically a corporate email matching the affiliation listed on the page, or an email at the domain referenced in the self-published source.
        </p>
      </section>

      <section className="mb-10" aria-label="Process">
        <h2 className="text-xl font-semibold text-gray-100 mb-3">How to request removal</h2>
        <p className="text-gray-400 text-sm leading-relaxed mb-3">
          Email{" "}
          <a
            href="mailto:opt-out@gitdealflow.com?subject=Founder%20profile%20opt-out%20request"
            className="text-sky-400 hover:text-sky-300"
          >
            opt-out@gitdealflow.com
          </a>{" "}
          with:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-gray-400 text-sm leading-relaxed">
          <li>The exact URL of the /founder/[handle] page you want removed.</li>
          <li>A statement that you are the person profiled.</li>
          <li>Verification, sent from an email at a domain that matches the affiliation or the self-published source already cited on the page.</li>
        </ul>
      </section>

      <section className="mb-10" aria-label="Outcome">
        <h2 className="text-xl font-semibold text-gray-100 mb-3">What happens next</h2>
        <ul className="list-disc pl-6 space-y-2 text-gray-400 text-sm leading-relaxed">
          <li>Within 7 business days of verification, the page is removed.</li>
          <li>The URL then returns HTTP 410 Gone (not 404), signaling to search engines that the page intentionally no longer exists.</li>
          <li>The handle is added to a permanent blocklist so the page cannot be re-generated by future content updates.</li>
          <li>You receive a confirmation email when the removal is complete.</li>
        </ul>
      </section>

      <section className="mb-10" aria-label="Scope">
        <h2 className="text-xl font-semibold text-gray-100 mb-3">Scope of this opt-out</h2>
        <p className="text-gray-400 text-sm leading-relaxed">
          This opt-out covers the /founder/[handle] entity page only. It does not remove the underlying public GitHub data (that data is hosted by GitHub, not by us). It does not remove your name from public-figure mentions inside other articles where the mention is incidental to the article's topic. For those cases, contact us at{" "}
          <a
            href="mailto:opt-out@gitdealflow.com"
            className="text-sky-400 hover:text-sky-300"
          >
            opt-out@gitdealflow.com
          </a>{" "}
          and we will review on a case-by-case basis.
        </p>
      </section>

      <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-5">
        <p className="text-xs font-medium text-gray-400 uppercase tracking-wider mb-2">
          Why this opt-out exists
        </p>
        <p className="text-gray-400 text-sm leading-relaxed">
          /founder/[handle] pages are restricted to public figures who self-publish their GitHub handle. The opt-out exists so that anyone in that group can have the page removed at any time without explanation, public-figure status today does not require permanent indexability.
        </p>
      </div>
    </div>
  );
}
