#!/usr/bin/env python3
"""Launcher for Dream Customers CRM dashboard.

Reads PB creds (env vars > monitoring/dream-customers/.env.local > email-api/.env),
auths with PB, writes dashboard.config.js (gitignored) with the impersonation
token, then opens dashboard.html in the default browser.

The dashboard reads dashboard.config.js via a regular <script> tag and uses the
token for all PB REST calls. Re-run this launcher to refresh the token
(default PB token TTL is 14 days for superusers).
"""

import json
import os
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
CONFIG_PATH = os.path.join(SCRIPT_DIR, "dashboard.config.js")
DASHBOARD_PATH = os.path.join(SCRIPT_DIR, "dashboard.html")


def load_env(path):
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def get_creds():
    if os.environ.get("PB_EMAIL") and os.environ.get("PB_PASSWORD"):
        return {
            "url": os.environ.get("PB_URL", "http://127.0.0.1:8090"),
            "email": os.environ["PB_EMAIL"],
            "password": os.environ["PB_PASSWORD"],
        }
    for path in [
        os.path.join(SCRIPT_DIR, ".env.local"),
        os.path.join(REPO_ROOT, "email-api", ".env"),
    ]:
        if os.path.exists(path):
            env = load_env(path)
            if env.get("PB_EMAIL") and env.get("PB_PASSWORD"):
                return {
                    "url": env.get("PB_URL", "http://127.0.0.1:8090"),
                    "email": env["PB_EMAIL"],
                    "password": env["PB_PASSWORD"],
                }
    raise RuntimeError(
        "No PB creds found. Set PB_EMAIL + PB_PASSWORD env vars, or create "
        f"{os.path.join(SCRIPT_DIR, '.env.local')} with PB_EMAIL/PB_PASSWORD/PB_URL."
    )


def auth(url, email, password):
    body = json.dumps({"identity": email, "password": password}).encode()
    req = urllib.request.Request(
        f"{url.rstrip('/')}/api/collections/_superusers/auth-with-password",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())["token"]


def main():
    creds = get_creds()
    print(f"Auth… ({creds['url']})")
    token = auth(creds["url"], creds["email"], creds["password"])

    config_js = (
        f"// Auto-generated by launch.py — do NOT commit.\n"
        f"window.PB_CONFIG = {{\n"
        f"  url: \"{creds['url']}\",\n"
        f"  token: {json.dumps(token)},\n"
        f"  generated_at: \"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\"\n"
        f"}};\n"
    )
    with open(CONFIG_PATH, "w") as f:
        f.write(config_js)
    print(f"Wrote {CONFIG_PATH}")

    print(f"Opening {DASHBOARD_PATH}")
    subprocess.run(["open", DASHBOARD_PATH], check=False)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
