#!/usr/bin/env node
/**
 * Generate The Data Nerd audio clips from tools/audio/scripts/*.txt and
 * write MP3 + manifest into pseo-site/public/audio/data-nerd/ and
 * pseo-site/lib/data-nerd-manifest.ts.
 *
 * Usage:
 *   node tools/audio/generate.mjs                    # regenerate all
 *   node tools/audio/generate.mjs story              # only story.mp3
 *   node tools/audio/generate.mjs --skip-existing    # only write missing clips
 *
 * Manifest is checked into git as a TypeScript module so the React
 * component can `import` it at build time without runtime fs access.
 */
import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  statSync,
} from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ttsToMp3Buffer, dataNerdVoice, assertVoiceConfigured } from "../lib/data-nerd-voice.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCRIPTS_DIR = path.join(__dirname, "scripts");
const REPO_ROOT = path.resolve(__dirname, "../..");
const PUBLIC_AUDIO_DIR = path.join(REPO_ROOT, "pseo-site/public/audio/data-nerd");
const MANIFEST_TS_PATH = path.join(REPO_ROOT, "pseo-site/lib/data-nerd-manifest.ts");
const MANIFEST_JSON_PATH = path.join(PUBLIC_AUDIO_DIR, "manifest.json");

const args = process.argv.slice(2);
const skipExisting = args.includes("--skip-existing");
const onlySlug = args.find((a) => !a.startsWith("--"));

if (!existsSync(PUBLIC_AUDIO_DIR)) mkdirSync(PUBLIC_AUDIO_DIR, { recursive: true });

function probeDurationSec(mp3Path) {
  try {
    const out = execFileSync(
      "ffprobe",
      ["-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", mp3Path],
      { encoding: "utf8" }
    );
    return Number(out.trim());
  } catch {
    return 0;
  }
}

function loadExistingManifest() {
  if (!existsSync(MANIFEST_JSON_PATH)) return { clips: {} };
  try {
    const m = JSON.parse(readFileSync(MANIFEST_JSON_PATH, "utf8"));
    return { clips: m.clips || {} };
  } catch {
    return { clips: {} };
  }
}

const scripts = readdirSync(SCRIPTS_DIR)
  .filter((f) => f.endsWith(".txt"))
  .map((f) => ({ slug: f.replace(/\.txt$/, ""), path: path.join(SCRIPTS_DIR, f) }))
  .filter((s) => !onlySlug || s.slug === onlySlug)
  .sort((a, b) => a.slug.localeCompare(b.slug));

if (scripts.length === 0) {
  console.error(onlySlug ? `no script matching ${onlySlug}` : "no scripts in tools/audio/scripts/");
  process.exit(1);
}

const existing = loadExistingManifest();

const willCallCartesia = scripts.some((s) => {
  if (!skipExisting) return true;
  const out = path.join(PUBLIC_AUDIO_DIR, `${s.slug}.mp3`);
  return !existsSync(out);
});

if (willCallCartesia) assertVoiceConfigured();

console.log(`Voice: ${dataNerdVoice.voiceName} (${dataNerdVoice.modelId})`);
console.log(`Out:   ${path.relative(REPO_ROOT, PUBLIC_AUDIO_DIR)}/`);
console.log(`Clips: ${scripts.length}${skipExisting ? " (skip-existing)" : ""}\n`);

const clips = { ...existing.clips };

for (const s of scripts) {
  const transcript = readFileSync(s.path, "utf8").trim();
  if (!transcript) {
    console.log(`  ${s.slug.padEnd(36)} (empty, skip)`);
    continue;
  }

  const outFile = path.join(PUBLIC_AUDIO_DIR, `${s.slug}.mp3`);

  if (skipExisting && existsSync(outFile)) {
    const durationSec = probeDurationSec(outFile);
    const bytes = statSync(outFile).size;
    clips[s.slug] = {
      ...(clips[s.slug] || {}),
      durationSec,
      bytes,
      chars: transcript.length,
    };
    console.log(`  ${s.slug.padEnd(36)} ${durationSec.toFixed(1)}s · ${(bytes / 1024).toFixed(0)}KB · (skip)`);
    continue;
  }

  const t = Date.now();
  const buf = await ttsToMp3Buffer(transcript);
  writeFileSync(outFile, buf);
  const durationSec = probeDurationSec(outFile);
  clips[s.slug] = {
    durationSec,
    bytes: buf.length,
    chars: transcript.length,
    generatedAt: new Date().toISOString(),
  };
  console.log(
    `  ${s.slug.padEnd(36)} ${durationSec.toFixed(1)}s · ${(buf.length / 1024).toFixed(0)}KB · ${Date.now() - t}ms`
  );
}

const manifest = {
  voice: { name: dataNerdVoice.voiceName, model: dataNerdVoice.modelId },
  generatedAt: new Date().toISOString(),
  clips,
};

writeFileSync(MANIFEST_JSON_PATH, JSON.stringify(manifest, null, 2));

const tsBody = `/**
 * Auto-generated by tools/audio/generate.mjs. Do not edit by hand.
 * Run \`node tools/audio/generate.mjs\` to regenerate.
 */
export type DataNerdClip = {
  durationSec: number;
  bytes: number;
  chars: number;
  generatedAt?: string;
};

export type DataNerdManifest = {
  voice: { name: string; model: string };
  generatedAt: string;
  clips: Record<string, DataNerdClip>;
};

export const dataNerdManifest: DataNerdManifest = ${JSON.stringify(manifest, null, 2)};
`;
writeFileSync(MANIFEST_TS_PATH, tsBody);

console.log(`\nWrote ${path.relative(REPO_ROOT, MANIFEST_JSON_PATH)}`);
console.log(`Wrote ${path.relative(REPO_ROOT, MANIFEST_TS_PATH)}`);
